[general]
import = [
    "./nvim-generated-colorscheme.toml"
]
live_config_reload = true


[window]
dimensions.columns = 100
dimensions.lines = 30
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 15

[cursor]
style.shape="Block"

[terminal]
osc52="CopyPaste"
