# Paolo Bignardi - Kitty config file

# font configuration
# font_family		BlexMono Nerd Font
font_family		Iosevka
font_size 		15.0
# nerd font symbol map
symbol_map  U+E000-U+E00D Symbols Nerd Font
symbol_map U+e0a0-U+e0a2,U+e0b0-U+e0b3 Symbols Nerd Font
symbol_map U+e0a3-U+e0a3,U+e0b4-U+e0c8,U+e0cc-U+e0d2,U+e0d4-U+e0d4 Symbols Nerd Font
symbol_map U+e5fa-U+e62b Symbols Nerd Font
symbol_map U+e700-U+e7c5 Symbols Nerd Font
symbol_map U+f000-U+f2e0 Symbols Nerd Font
symbol_map U+e200-U+e2a9 Symbols Nerd Font
symbol_map U+f400-U+f4a8,U+2665-U+2665,U+26A1-U+26A1,U+f27c-U+f27c Symbols Nerd Font
symbol_map U+F300-U+F313 Symbols Nerd Font
symbol_map U+23fb-U+23fe,U+2b58-U+2b58 Symbols Nerd Font
symbol_map U+f500-U+fd46 Symbols Nerd Font
symbol_map U+e300-U+e3eb Symbols Nerd Font
symbol_map U+21B5,U+25B8,U+2605,U+2630,U+2632,U+2714,U+E0A3,U+E615,U+E62B Symbols Nerd Font

# cursor configuration
shell_integration	no-cursor
cursor_shape		block
cursor_blink_interval 	0

# scrollback configuration
scrollback_lines 	3000
wheel_scroll_multiplier 10.0

# link underline
underline_hyperlinks 	always

# strip trailing spaces
strip_trailing_spaces 	smart

# set editor as neovim
editor 			nvim

include gruvbox_dark_hard.conf

# tab configuration
tab_bar_style 		powerline
tab_powerline_style 	slanted
