# Paolo Bignardi - Kitty config file

# FONT CONFIG
# font_family      family="IBM Plex Mono"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size 		    15.0

# symbol map
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E600-U+E6C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F372,U+F400-U+F532,U+F0001-U+F1AF0 Symbols Nerd Font Mono

# cursor configuration
shell_integration	no-cursor
cursor_shape		block
cursor_blink_interval 	0

# scrollback configuration
scrollback_lines 	3000
wheel_scroll_multiplier 10.0

# link underline
underline_hyperlinks 	always

# strip trailing spaces
strip_trailing_spaces 	smart

# change kitty_mod
kitty_mod           alt+shift

# set editor as neovim
editor 			    nvim

# include kitty-themes/themes/OneDark_Warmer.conf
include nordic.conf

# disable tabs
map super+t discard_event

# remote control
allow_remote_control    socket-only

# setup kitty scrollback
listen_on unix:/tmp/kitty


# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /Users/paolo/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output


# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

map ctrl+k kitten mykitten.py
