[colors.primary]
background = "#232326"
foreground = "#a7aab0"

[colors.normal]
black = "#101012"
red = "#de5d68"
green = "#8fb573"
yellow = "#dbb671"
blue = "#57a5e5"
magenta = "#bb70d2"
cyan = "#51a8b3"
white = '#BDC5BD'

[colors.bright]
black = "#5a5b5e"
red = "#de5d68"
green = "#8fb573"
yellow = "#e2c792"
blue = "#68aee8"
magenta = "#bb70d2"
cyan = "#51a8b3"
white = '#BDC5BD'

[colors.selection]
text = '#000000'
background = '#F0DFAF'
