-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim
local palette = {
	base00 = "#151515",
	base01 = "#202020",
	base02 = "#303030",
	base03 = "#505050",
	base04 = "#b0b0b0",
	base05 = "#d0d0d0",
	base06 = "#e0e0e0",
	base07 = "#f5f5f5",
	base08 = "#fb9fb1",
	base09 = "#eda987",
	base0A = "#ddb26f",
	base0B = "#acc267",
	base0C = "#12cfc0",
	base0D = "#6fc2ef",
	base0E = "#e1a3ee",
	base0F = "#deaf8f",
}

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "chalk"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@keyword.return", { fg = "#ff9ea2" })
hi(0, "@lsp.mod.deprecated", { fg = "#ff9ea2" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { fg = "#d0d0d0" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@string.special.vimdoc", { link = "SpecialChar" })
hi(0, "@symbol", { fg = "#ed9ee5" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { fg = "#d0d0d0" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "@variable.parameter.vimdoc", { fg = "#ecaa7a" })
hi(0, "Added", { ctermfg = 10, fg = "#bbbe54" })
hi(0, "Beacon", { bg = "#f5f5f5" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ecaa7a" })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { bg = "#202020", fg = "#5dc6eb" })
hi(0, "BqfSign", { bg = "#202020", fg = "#2ecfb0" })
hi(0, "BufferCurrent", { bg = "#303030", bold = true, fg = "#d0d0d0" })
hi(0, "BufferCurrentIcon", { bg = "#303030" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#303030", bold = true, fg = "#ff9ea2" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#303030", bold = true, fg = "#ed9ee5" })
hi(0, "BufferInactive", { bg = "#202020", fg = "#b0b0b0" })
hi(0, "BufferInactiveIcon", { bg = "#202020" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#202020", fg = "#ff9ea2" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#202020", bold = true, fg = "#ed9ee5" })
hi(0, "BufferLineBuffer", { fg = "#b0b0b0" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#d0d0d0" })
hi(0, "BufferLineBufferVisible", { fg = "#d0d0d0" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#ddb26f", fg = "#151515" })
hi(0, "BufferLineTabSelected", { bg = "#ddb26f", bold = true, fg = "#151515" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#ddb26f", bold = true, fg = "#202020" })
hi(0, "BufferVisible", { bg = "#202020", bold = true, fg = "#d0d0d0" })
hi(0, "BufferVisibleIcon", { bg = "#202020" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#202020", bold = true, fg = "#ff9ea2" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#202020", bold = true, fg = "#ed9ee5" })
hi(0, "Changed", { ctermfg = 14, fg = "#ed9ee5" })
hi(0, "Character", { fg = "#ff9ea2" })
hi(0, "CmpItemAbbr", { fg = "#d0d0d0" })
hi(0, "CmpItemAbbrDefault", { fg = "#d0d0d0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#505050" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#505050" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#d7b665" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#d0d0d0" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#d7b665" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#d0d0d0" })
hi(0, "CmpItemKind", { bg = "#202020", fg = "#ddb185" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#2ecfb0" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Statement" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "CmpItemMenuDefault", { fg = "#d0d0d0" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#ddb185" })
hi(0, "CocMenuSel", { bg = "#303030" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#d7b665" })
hi(0, "CocSelectedText", { fg = "#ff9ea2" })
hi(0, "ColorColumn", { bg = "#202020" })
hi(0, "Comment", { fg = "#505050" })
hi(0, "Conceal", { fg = "#5dc6eb" })
hi(0, "Conditional", { fg = "#ed9ee5" })
hi(0, "Constant", { fg = "#ecaa7a" })
hi(0, "CurSearch", { bg = "#eda987", ctermbg = 11, ctermfg = 0, fg = "#202020" })
hi(0, "Cursor", { bg = "#d0d0d0", fg = "#151515" })
hi(0, "CursorColumn", { bg = "#202020" })
hi(0, "CursorIM", { bg = "#d0d0d0", fg = "#151515" })
hi(0, "CursorLine", { bg = "#202020", ctermbg = 6 })
hi(0, "CursorLineFold", { bg = "#202020", fg = "#2ecfb0" })
hi(0, "CursorLineNr", { bg = "#202020", fg = "#b0b0b0" })
hi(0, "CursorLineSign", { bg = "#202020", fg = "#505050" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#bbbe54" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#ed9ee5" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Title" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Debug", { fg = "#ff9ea2" })
hi(0, "Define", { fg = "#ed9ee5" })
hi(0, "Definitions", { fg = "#bbbe54" })
hi(0, "DefinitionsIcon", { fg = "#5dc6eb" })
hi(0, "Delimiter", { fg = "#ddb185" })
hi(0, "DiagnosticError", { ctermfg = 9, fg = "#ff9ea2" })
hi(0, "DiagnosticFloatingError", { bg = "#202020", fg = "#ff9ea2" })
hi(0, "DiagnosticFloatingHint", { bg = "#202020", fg = "#5dc6eb" })
hi(0, "DiagnosticFloatingInfo", { bg = "#202020", fg = "#2ecfb0" })
hi(0, "DiagnosticFloatingOk", { bg = "#202020", fg = "#bbbe54" })
hi(0, "DiagnosticFloatingWarn", { bg = "#202020", fg = "#ddb26f" })
hi(0, "DiagnosticHint", { ctermfg = 12, fg = "#5dc6eb" })
hi(0, "DiagnosticInfo", { ctermfg = 14, fg = "#2ecfb0" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#bbbe54" })
hi(0, "DiagnosticSignError", { link = "DiagnosticFloatingError" })
hi(0, "DiagnosticSignHint", { link = "DiagnosticFloatingHint" })
hi(0, "DiagnosticSignInfo", { link = "DiagnosticFloatingInfo" })
hi(0, "DiagnosticSignOk", { link = "DiagnosticFloatingOk" })
hi(0, "DiagnosticSignWarn", { link = "DiagnosticFloatingWarn" })
hi(0, "DiagnosticUnderlineError", { sp = "#fb9fb1", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6fc2ef", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#12cfc0", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#acc267", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ddb26f", underline = true })
hi(0, "DiagnosticWarn", { ctermfg = 11, fg = "#ddb26f" })
hi(0, "DiffAdd", { bg = "#202020", ctermbg = 10, ctermfg = 0, fg = "#bbbe54" })
hi(0, "DiffChange", { bg = "#202020", fg = "#6fc2ef" })
hi(0, "DiffDelete", { bg = "#202020", ctermfg = 9, fg = "#ff9ea2" })
hi(0, "DiffText", { bg = "#202020", ctermbg = 14, ctermfg = 0, fg = "#b0b0b0" })
hi(0, "Directory", { ctermfg = 14, fg = "#5dc6eb" })
hi(0, "EndOfBuffer", { fg = "#505050" })
hi(0, "Error", { bg = "#fb9fb1", ctermbg = 9, ctermfg = 0, fg = "#151515" })
hi(0, "ErrorMsg", { bg = "#151515", ctermfg = 9, fg = "#ff9ea2" })
hi(0, "Exception", { fg = "#ff9ea2" })
hi(0, "FinderParam", { fg = "#ff9ea2" })
hi(0, "FinderSpinner", { fg = "#bbbe54" })
hi(0, "FinderSpinnerBorder", { fg = "#ddb185" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#ecaa7a" })
hi(0, "Float", { fg = "#ecaa7a" })
hi(0, "FoldColumn", { bg = "#202020", fg = "#2ecfb0" })
hi(0, "Folded", { bg = "#202020", fg = "#505050" })
hi(0, "Function", { ctermfg = 14, fg = "#5dc6eb" })
hi(0, "FzfLuaBackdrop", { bg = "#000000" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#96f7f5" })
hi(0, "FzfLuaBufFlagCur", { fg = "#fc4300" })
hi(0, "FzfLuaBufNr", { fg = "#faedcb" })
hi(0, "FzfLuaHeaderBind", { fg = "#faedcb" })
hi(0, "FzfLuaHeaderText", { fg = "#fc4300" })
hi(0, "FzfLuaLivePrompt", { fg = "#ff7e98" })
hi(0, "FzfLuaLiveSym", { fg = "#ff7e98" })
hi(0, "FzfLuaPathColNr", { fg = "#96f7f5" })
hi(0, "FzfLuaPathLineNr", { fg = "#a4eb73" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#faedcb" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#a9e4fa" })
hi(0, "GitSignsAdd", { bg = "#202020", fg = "#bbbe54" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { bg = "#202020", fg = "#6fc2ef" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { bg = "#202020", fg = "#ff9ea2" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsStagedAdd", { bg = "#202020", fg = "#5e5e2a" })
hi(0, "GitSignsStagedAddCul", { bg = "#202020", fg = "#5e5e2a" })
hi(0, "GitSignsStagedAddLn", { bg = "#202020", fg = "#5e5e2a" })
hi(0, "GitSignsStagedAddNr", { bg = "#202020", fg = "#5e5e2a" })
hi(0, "GitSignsStagedChange", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangeCul", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangeLn", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangeNr", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangedelete", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangedeleteCul", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedDelete", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedDeleteCul", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedTopdelete", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedTopdeleteCul", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedTopdeleteLn", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#202020", fg = "#824c4f" })
hi(0, "GitSignsStagedUntracked", { bg = "#202020", fg = "#794c74" })
hi(0, "GitSignsStagedUntrackedCul", { bg = "#202020", fg = "#5e5e2a" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#202020", fg = "#2d6375" })
hi(0, "GitSignsStagedUntrackedNr", { bg = "#202020", fg = "#5e5e2a" })
hi(0, "GitSignsUntracked", { bg = "#202020", fg = "#ed9ee5" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#ed9ee5", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#ff9ea2", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#b0b0b0", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#ecaa7a", nocombine = true })
hi(0, "HopUnmatched", { link = "Comment" })
hi(0, "HydraAmaranth", { fg = "#ed9ee5" })
hi(0, "HydraBlue", { fg = "#5dc6eb" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#ecaa7a" })
hi(0, "HydraRed", { fg = "#ff9ea2" })
hi(0, "HydraTeal", { fg = "#bbbe54" })
hi(0, "Identifier", { ctermfg = 12, fg = "#ff9ea2" })
hi(0, "Ignore", { fg = "#2ecfb0" })
hi(0, "IncSearch", { bg = "#eda987", fg = "#202020" })
hi(0, "Include", { fg = "#5dc6eb" })
hi(0, "IndentBlanklineChar", { fg = "#303030", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#ddb185", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#deaf8f", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#ff9ea2", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#ecaa7a", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#d7b665", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#bbbe54", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#2ecfb0", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#5dc6eb", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#ed9ee5", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#ddb185", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#ed9ee5" })
hi(0, "LSOutlinePreviewBorder", { fg = "#ddb185" })
hi(0, "Label", { fg = "#d7b665" })
hi(0, "LazyButton", { bg = "#202020" })
hi(0, "LazyButtonActive", { bg = "#303030" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#303030", bold = true })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#ff9ea2", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#ecaa7a", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#ed9ee5", nocombine = true, underline = true })
hi(0, "LightspeedCursor", { link = "Cursor" })
hi(0, "LightspeedGreyWash", { link = "Comment" })
hi(0, "LightspeedLabel", { bold = true, fg = "#ed9ee5", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#5dc6eb", underline = true })
hi(0, "LightspeedMaskedChar", { fg = "#b0b0b0" })
hi(0, "LightspeedOneCharMatch", { link = "LightspeedShortcut" })
hi(0, "LightspeedPendingOpArea", { link = "IncSearch" })
hi(0, "LightspeedShortcut", { bold = true, fg = "#f5f5f5" })
hi(0, "LightspeedUniqueChar", { link = "LightspeedUnlabeledMatch" })
hi(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#d0d0d0" })
hi(0, "LineNr", { bg = "#202020", fg = "#505050" })
hi(0, "LineNrAbove", { bg = "#202020", fg = "#505050" })
hi(0, "LineNrBelow", { bg = "#202020", fg = "#505050" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#303030" })
hi(0, "LspSagaAutoPreview", { fg = "#ddb185" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { fg = "#ddb185" })
hi(0, "LspSagaCodeActionContent", { fg = "#d0d0d0" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#5dc6eb" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#ddb185" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#ddb185" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#ed9ee5" })
hi(0, "LspSagaFinderSelection", { fg = "#d7b665" })
hi(0, "LspSagaHoverBorder", { fg = "#ddb185" })
hi(0, "LspSagaLspFinderBorder", { fg = "#ddb185" })
hi(0, "LspSagaRenameBorder", { fg = "#ddb185" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#ddb185" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "Macro", { fg = "#ff9ea2" })
hi(0, "MasonError", { fg = "#ff9ea2" })
hi(0, "MasonHeader", { bg = "#6fc2ef", bold = true, fg = "#151515" })
hi(0, "MasonHeaderSecondary", { bg = "#deaf8f", bold = true, fg = "#151515" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#ddb185" })
hi(0, "MasonHighlightBlock", { bg = "#deaf8f", fg = "#151515" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#6fc2ef", fg = "#151515" })
hi(0, "MasonHighlightSecondary", { fg = "#5dc6eb" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#505050", fg = "#151515" })
hi(0, "MasonMutedBlockBold", { bg = "#505050", bold = true, fg = "#151515" })
hi(0, "MatchParen", { bg = "#303030" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "NormalFloat" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#202020", bold = true, fg = "#5dc6eb" })
hi(0, "MiniCompletionActiveParameter", { bg = "#303030" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { link = "DiffAdd" })
hi(0, "MiniDiffSignChange", { link = "DiffChange" })
hi(0, "MiniDiffSignDelete", { link = "DiffDelete" })
hi(0, "MiniFilesBorder", { link = "NormalFloat" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { bg = "#303030" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#d0d0d0" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { bg = "#202020", fg = "#5dc6eb" })
hi(0, "MiniFilesTitleFocused", { bg = "#202020", bold = true, fg = "#5dc6eb" })
hi(0, "MiniHipatternsFixme", { bg = "#fb9fb1", bold = true, fg = "#151515" })
hi(0, "MiniHipatternsHack", { bg = "#e1a3ee", bold = true, fg = "#151515" })
hi(0, "MiniHipatternsNote", { bg = "#6fc2ef", bold = true, fg = "#151515" })
hi(0, "MiniHipatternsTodo", { bg = "#ddb26f", bold = true, fg = "#151515" })
hi(0, "MiniIconsAzure", { fg = "#5dc6eb" })
hi(0, "MiniIconsBlue", { fg = "#ddb185" })
hi(0, "MiniIconsCyan", { fg = "#2ecfb0" })
hi(0, "MiniIconsGreen", { fg = "#bbbe54" })
hi(0, "MiniIconsGrey", { fg = "#f5f5f5" })
hi(0, "MiniIconsOrange", { fg = "#ecaa7a" })
hi(0, "MiniIconsPurple", { fg = "#ed9ee5" })
hi(0, "MiniIconsRed", { fg = "#ff9ea2" })
hi(0, "MiniIconsYellow", { fg = "#d7b665" })
hi(0, "MiniIndentscopeSymbol", { fg = "#303030" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#ff9ea2" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bg = "#202020", bold = true, fg = "#f5f5f5", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#151515", fg = "#e0e0e0", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "MiniMapSymbolCount", { fg = "#2ecfb0" })
hi(0, "MiniMapSymbolLine", { fg = "#5dc6eb" })
hi(0, "MiniMapSymbolView", { fg = "#ddb185" })
hi(0, "MiniNotifyBorder", { fg = "#5dc6eb", bg = "#151515" })
hi(0, "MiniNotifyNormal", { fg = "#505050", bg = "#151515" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "NormalFloat" })
hi(0, "MiniPickBorderBusy", { bg = "#202020", fg = "#ed9ee5" })
hi(0, "MiniPickBorderText", { bg = "#202020", bold = true, fg = "#5dc6eb" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { fg = "#d0d0d0" })
hi(0, "MiniPickMatchCurrent", { bg = "#303030" })
hi(0, "MiniPickMatchMarked", { bg = "#505050" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { bg = "#303030" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#202020", fg = "#bbbe54" })
hi(0, "MiniSnippetsCurrent", { sp = "#e1a3ee", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#fb9fb1", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#acc267", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#6fc2ef", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#12cfc0", underdouble = true })
hi(0, "MiniStarterFooter", { fg = "#5dc6eb" })
hi(0, "MiniStarterHeader", { fg = "#5dc6eb" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { fg = "#d0d0d0" })
hi(0, "MiniStarterItemBullet", { fg = "#ddb185" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#ff9ea2" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#bbbe54" })
hi(0, "MiniStarterSection", { fg = "#ddb185" })
hi(0, "MiniStatuslineDevinfo", { bg = "#303030", fg = "#b0b0b0" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineDiagnostic", { bg = "#505050", fg = "#b0b0b0" })
hi(0, "MiniStatuslineFilename", { bg = "#202020", fg = "#505050" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#fb9fb1", bold = true, fg = "#151515" })
hi(0, "MiniStatuslineModeInsert", { bg = "#6fc2ef", bold = true, fg = "#151515" })
hi(0, "MiniStatuslineModeNormal", { bg = "#d0d0d0", bold = true, fg = "#151515" })
hi(0, "MiniStatuslineModeOther", { bg = "#505050", bold = true, fg = "#151515" })
hi(0, "MiniStatuslineModeReplace", { bg = "#e1a3ee", bold = true, fg = "#151515" })
hi(0, "MiniStatuslineModeVisual", { bg = "#acc267", bold = true, fg = "#151515" })
hi(0, "MiniTablineCurrent", { bg = "#303030", bold = true, fg = "#d0d0d0" })
hi(0, "MiniTablineHidden", { bg = "#202020", fg = "#b0b0b0" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#d0d0d0", bold = true, fg = "#303030" })
hi(0, "MiniTablineModifiedHidden", { bg = "#b0b0b0", fg = "#202020" })
hi(0, "MiniTablineModifiedVisible", { bg = "#b0b0b0", bold = true, fg = "#303030" })
hi(0, "MiniTablineTabpagesection", { bg = "#ddb26f", bold = true, fg = "#202020" })
hi(0, "MiniTablineVisible", { bg = "#202020", bold = true, fg = "#d0d0d0" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff9ea2" })
hi(0, "MiniTestPass", { bold = true, fg = "#bbbe54" })
hi(0, "ModeMsg", { ctermfg = 10, fg = "#bbbe54" })
hi(0, "MoreMsg", { ctermfg = 14, fg = "#bbbe54" })
hi(0, "MsgArea", { bg = "#151515", fg = "#d0d0d0" })
hi(0, "MsgSeparator", { bg = "#303030", fg = "#b0b0b0" })
hi(0, "NeoTreeDimText", { fg = "#505050" })
hi(0, "NeoTreeDotfile", { fg = "#b0b0b0" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#303030" })
hi(0, "NeoTreeGitAdded", { fg = "#bbbe54" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#ff9ea2" })
hi(0, "NeoTreeGitDeleted", { fg = "#ff9ea2" })
hi(0, "NeoTreeGitModified", { fg = "#ed9ee5" })
hi(0, "NeoTreeGitUnstaged", { fg = "#ff9ea2" })
hi(0, "NeoTreeGitUntracked", { fg = "#d7b665" })
hi(0, "NeoTreeMessage", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "NeoTreeModified", { fg = "#f5f5f5" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#5dc6eb" })
hi(0, "NeoTreeTabInactive", { fg = "#b0b0b0" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#303030", fg = "#505050" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#202020", fg = "#202020" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#5dc6eb" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#5dc6eb" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceAttr85", { bg = "#151515", fg = "#ff9ea2" })
hi(0, "NoiceAttr90", { bg = "#151515", fg = "#d0d0d0" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#5dc6eb" })
hi(0, "NoiceConfirmBorder", { fg = "#ed9ee5" })
hi(0, "NoiceFormatProgressDone", { bg = "#ddb26f", fg = "#202020" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#505050" })
hi(0, "Normal", { bg = "#151515", fg = "#d0d0d0" })
hi(0, "NormalFloat", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "NormalNC", { bg = "#151515", fg = "#d0d0d0" })
hi(0, "NotifyDEBUGBorder", { fg = "#505050" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#ff9ea2" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#2ecfb0" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#5dc6eb" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#ed9ee5" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "Number", { fg = "#ecaa7a" })
hi(0, "NvimInternalError", { bg = "#ff0000", ctermbg = 9, ctermfg = 9, fg = "#e74d00" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#bbbe54" })
hi(0, "NvimTreeFolderIcon", { fg = "#505050" })
hi(0, "NvimTreeGitDeleted", { fg = "#ff9ea2" })
hi(0, "NvimTreeGitDirty", { fg = "#ff9ea2" })
hi(0, "NvimTreeGitMerge", { fg = "#2ecfb0" })
hi(0, "NvimTreeGitNew", { fg = "#d7b665" })
hi(0, "NvimTreeGitRenamed", { fg = "#ed9ee5" })
hi(0, "NvimTreeGitStaged", { fg = "#bbbe54" })
hi(0, "NvimTreeImageFile", { bold = true, fg = "#ed9ee5" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#5dc6eb", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#ddb185" })
hi(0, "NvimTreeWindowPicker", { bg = "#202020", bold = true, fg = "#d0d0d0" })
hi(0, "Operator", { fg = "#d0d0d0" })
hi(0, "OutlineDetail", { fg = "#505050" })
hi(0, "OutlineFoldPrefix", { fg = "#ff9ea2" })
hi(0, "OutlineIndentEvn", { fg = "#b0b0b0" })
hi(0, "OutlineIndentOdd", { fg = "#d0d0d0" })
hi(0, "Pmenu", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "PmenuExtra", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "PmenuExtraSel", { bg = "#202020", fg = "#d0d0d0", reverse = true })
hi(0, "PmenuKind", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "PmenuKindSel", { bg = "#202020", fg = "#d0d0d0", reverse = true })
hi(0, "PmenuMatch", { bg = "#202020", bold = true, fg = "#d0d0d0" })
hi(0, "PmenuMatchSel", { bg = "#202020", bold = true, fg = "#d0d0d0", reverse = true })
hi(0, "PmenuSbar", { bg = "#303030" })
hi(0, "PmenuSel", { bg = "#202020", fg = "#d0d0d0", reverse = true })
hi(0, "PmenuThumb", { bg = "#f5f5f5" })
hi(0, "PounceAccept", { bg = "#fb9fb1", bold = true, fg = "#151515", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#acc267", bold = true, fg = "#151515", nocombine = true })
hi(0, "PounceGap", { bg = "#505050", bold = true, fg = "#151515", nocombine = true })
hi(0, "PounceMatch", { bg = "#d0d0d0", bold = true, fg = "#151515", nocombine = true })
hi(0, "PreCondit", { fg = "#d7b665" })
hi(0, "PreProc", { fg = "#d7b665" })
hi(0, "Question", { ctermfg = 14, fg = "#5dc6eb" })
hi(0, "QuickFixLine", { bg = "#202020", ctermfg = 14 })
hi(0, "RainbowDelimiterBlue", { fg = "#5dc6eb" })
hi(0, "RainbowDelimiterCyan", { fg = "#2ecfb0" })
hi(0, "RainbowDelimiterGreen", { fg = "#bbbe54" })
hi(0, "RainbowDelimiterOrange", { fg = "#ecaa7a" })
hi(0, "RainbowDelimiterRed", { fg = "#ff9ea2" })
hi(0, "RainbowDelimiterViolet", { fg = "#ed9ee5" })
hi(0, "RainbowDelimiterYellow", { fg = "#d7b665" })
hi(0, "References", { fg = "#bbbe54" })
hi(0, "ReferencesIcon", { fg = "#5dc6eb" })
hi(0, "Removed", { ctermfg = 9, fg = "#ff9ea2" })
hi(0, "Repeat", { fg = "#d7b665" })
hi(0, "Search", { bg = "#ddb26f", ctermbg = 11, ctermfg = 0, fg = "#202020" })
hi(0, "SignColumn", { bg = "#202020", fg = "#505050" })
hi(0, "Sneak", { bg = "#e1a3ee", fg = "#151515" })
hi(0, "SneakLabel", { bg = "#e1a3ee", bold = true, fg = "#151515" })
hi(0, "SneakScope", { bg = "#f5f5f5", fg = "#151515" })
hi(0, "Special", { ctermfg = 14, fg = "#2ecfb0" })
hi(0, "SpecialChar", { fg = "#ddb185" })
hi(0, "SpecialComment", { fg = "#2ecfb0" })
hi(0, "SpecialKey", { fg = "#505050" })
hi(0, "SpellBad", { sp = "#fb9fb1", undercurl = true })
hi(0, "SpellCap", { sp = "#6fc2ef", undercurl = true })
hi(0, "SpellLocal", { sp = "#12cfc0", undercurl = true })
hi(0, "SpellRare", { sp = "#e1a3ee", undercurl = true })
hi(0, "Statement", { fg = "#ff9ea2" })
hi(0, "StatusLine", { bg = "#303030", fg = "#b0b0b0" })
hi(0, "StatusLineNC", { bg = "#202020", fg = "#505050" })
hi(0, "StorageClass", { fg = "#d7b665" })
hi(0, "String", { ctermfg = 10, fg = "#bbbe54" })
hi(0, "Structure", { fg = "#ed9ee5" })
hi(0, "Substitute", { bg = "#ddb26f", fg = "#202020" })
hi(0, "TabLine", { bg = "#202020", fg = "#505050" })
hi(0, "TabLineFill", { bg = "#202020", fg = "#505050" })
hi(0, "TabLineSel", { bg = "#202020", fg = "#bbbe54" })
hi(0, "Tag", { fg = "#d7b665" })
hi(0, "TargetFileName", { fg = "#d0d0d0" })
hi(0, "TelescopeBorder", { fg = "#d0d0d0" })
hi(0, "TelescopeMatching", { fg = "#d7b665" })
hi(0, "TelescopeMultiSelection", { bg = "#202020", bold = true })
hi(0, "TelescopeSelection", { bg = "#202020", bold = true })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#5dc6eb" })
hi(0, "Todo", { bg = "#202020", fg = "#d7b665" })
hi(0, "TooLong", { fg = "#ff9ea2" })
hi(0, "TroubleCount", { bold = true, fg = "#bbbe54" })
hi(0, "TroubleFoldIcon", { fg = "#d0d0d0" })
hi(0, "TroubleIndent", { fg = "#303030" })
hi(0, "TroubleLocation", { fg = "#b0b0b0" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#d0d0d0" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#d7b665" })
hi(0, "Typedef", { fg = "#d7b665" })
hi(0, "VenvSelectActiveVenv", { fg = "#91f200" })
hi(0, "VertSplit", { bg = "#303030", fg = "#303030" })
hi(0, "Visual", { bg = "#303030", ctermbg = 15, ctermfg = 0 })
hi(0, "VisualNOS", { fg = "#ff9ea2" })
hi(0, "WarningMsg", { ctermfg = 11, fg = "#ff9ea2" })
hi(0, "WhichKey", { fg = "#5dc6eb" })
hi(0, "WhichKeyDesc", { fg = "#d0d0d0" })
hi(0, "WhichKeyFloat", { bg = "#202020", fg = "#d0d0d0" })
hi(0, "WhichKeyGroup", { fg = "#ed9ee5" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeySeparator", { bg = "#202020", fg = "#bbbe54" })
hi(0, "WhichKeyValue", { fg = "#505050" })
hi(0, "Whitespace", { fg = "#505050" })
hi(0, "WildMenu", { bg = "#ddb26f", fg = "#ff9ea2" })
hi(0, "WinBar", { bg = "#303030", fg = "#b0b0b0" })
hi(0, "WinBarNC", { bg = "#202020", fg = "#505050" })
hi(0, "WinSeparator", { bg = "#303030", fg = "#303030" })
hi(0, "diffAdded", { fg = "#bbbe54" })
hi(0, "diffChanged", { fg = "#ed9ee5" })
hi(0, "diffFile", { fg = "#ecaa7a" })
hi(0, "diffLine", { fg = "#2ecfb0" })
hi(0, "diffRemoved", { fg = "#ff9ea2" })
hi(0, "gitcommitBranch", { bold = true, fg = "#ecaa7a" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#ff9ea2" })
hi(0, "gitcommitDiscardedType", { fg = "#5dc6eb" })
hi(0, "gitcommitHeader", { fg = "#ed9ee5" })
hi(0, "gitcommitOverflow", { fg = "#ff9ea2" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#bbbe54" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#bbbe54" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#d7b665" })
hi(0, "lCursor", { bg = "#d0d0d0", fg = "#151515" })
hi(0, "lualine_a_command", { bg = "#ffaec2", bold = true, fg = "#171717" })
hi(0, "lualine_a_inactive", { bg = "#e4e4e4", bold = true, fg = "#171717" })
hi(0, "lualine_a_insert", { bg = "#bdd571", bold = true, fg = "#171717" })
hi(0, "lualine_a_normal", { bg = "#e4e4e4", bold = true, fg = "#171717" })
hi(0, "lualine_a_replace", { bg = "#ffb994", bold = true, fg = "#171717" })
hi(0, "lualine_a_terminal", { bg = "#ffaec2", bold = true, fg = "#171717" })
hi(0, "lualine_a_visual", { bg = "#13e3d3", bold = true, fg = "#171717" })
hi(0, "lualine_b_command", { bg = "#171717", fg = "#ffacb6" })
hi(0, "lualine_b_diagnostics_error_command", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_error_inactive", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_error_insert", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_error_normal", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_error_replace", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_error_terminal", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_error_visual", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diagnostics_hint_command", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_hint_inactive", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_hint_insert", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_hint_normal", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_hint_replace", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_hint_terminal", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_hint_visual", { bg = "#171717", fg = "#5dc6eb" })
hi(0, "lualine_b_diagnostics_info_command", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_info_inactive", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_info_insert", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_info_normal", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_info_replace", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_info_terminal", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_info_visual", { bg = "#171717", fg = "#2ecfb0" })
hi(0, "lualine_b_diagnostics_warn_command", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diagnostics_warn_inactive", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diagnostics_warn_insert", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diagnostics_warn_normal", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diagnostics_warn_replace", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diagnostics_warn_terminal", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diagnostics_warn_visual", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_added_command", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_added_inactive", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_added_insert", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_added_normal", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_added_replace", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_added_terminal", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_added_visual", { bg = "#171717", fg = "#bbbe54" })
hi(0, "lualine_b_diff_modified_command", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_modified_inactive", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_modified_insert", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_modified_normal", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_modified_replace", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_modified_terminal", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_modified_visual", { bg = "#171717", fg = "#ed9ee5" })
hi(0, "lualine_b_diff_removed_command", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diff_removed_inactive", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diff_removed_insert", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diff_removed_normal", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diff_removed_replace", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diff_removed_terminal", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_diff_removed_visual", { bg = "#171717", fg = "#ff9ea2" })
hi(0, "lualine_b_inactive", { bg = "#171717", fg = "#e4e4e4" })
hi(0, "lualine_b_insert", { bg = "#171717", fg = "#cdd15c" })
hi(0, "lualine_b_normal", { bg = "#171717", fg = "#e4e4e4" })
hi(0, "lualine_b_replace", { bg = "#171717", fg = "#fabc89" })
hi(0, "lualine_b_terminal", { bg = "#171717", fg = "#ffacb6" })
hi(0, "lualine_b_visual", { bg = "#171717", fg = "#33e3c1" })
hi(0, "lualine_c_command", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_c_inactive", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_c_insert", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_c_normal", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_c_replace", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_c_terminal", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_c_visual", { bg = "#343434", fg = "#e4e4e4" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#171717", fg = "#ffacb6" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#171717", fg = "#e4e4e4" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_command", { bg = "#343434", fg = "#171717" })
hi(
	0,
	"lualine_transitional_lualine_b_diagnostics_warn_command_to_lualine_c_command",
	{ bg = "#343434", fg = "#171717" }
)
hi(0, "lualine_transitional_lualine_b_diagnostics_warn_normal_to_lualine_c_normal", { bg = "#343434", fg = "#171717" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#343434", fg = "#171717" })

hi(0, "RenderMarkdownH1", { fg = "#fb9fb1", bg = "#202020" })
hi(0, "RenderMarkdownH2", { fg = "#6fc2ef", bg = "#202020" })
hi(0, "RenderMarkdownH3", { fg = "#acc267", bg = "#202020" })
hi(0, "RenderMarkdownH4", { fg = "#ddb26f", bg = "#202020" })
hi(0, "RenderMarkdownH5", { fg = "#12cfc0", bg = "#202020" })
hi(0, "RenderMarkdownH6", { fg = "#e1a3ee", bg = "#202020" })

-- 3rd to last  element (with 10 midpoints)
hi(0, "RenderMarkdownH1Bg", { fg = "#fb9fb1", bg = "#3F2E31" })
hi(0, "RenderMarkdownH2Bg", { fg = "#6fc2ef", bg = "#25343D" })
hi(0, "RenderMarkdownH3Bg", { fg = "#acc267", bg = "#303424" })
hi(0, "RenderMarkdownH4Bg", { fg = "#ddb26f", bg = "#393225" })
hi(0, "RenderMarkdownH5Bg", { fg = "#12cfc0", bg = "#143734" })
hi(0, "RenderMarkdownH6Bg", { fg = "#e1a3ee", bg = "#3A2F3C" })

hi(0, "RenderMarkdownQuote", { fg = "#b0b0b0", bg = "#151515" })

hi(0, "RenderMarkdownTableHead", { fg = "#b0b0b0", bg = "#151515" })
hi(0, "RenderMarkdownTableRow", { link = "RenderMarkdownTableHead" })
hi(0, "RenderMarkdownTableFill", { link = "RenderMarkdownTableHead" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#151515"
g.terminal_color_1 = "#fb9fb1"
g.terminal_color_2 = "#acc267"
g.terminal_color_3 = "#ddb26f"
g.terminal_color_4 = "#6fc2ef"
g.terminal_color_5 = "#e1a3ee"
g.terminal_color_6 = "#12cfc0"
g.terminal_color_7 = "#d0d0d0"
g.terminal_color_8 = "#505050"
g.terminal_color_9 = "#fb9fb1"
g.terminal_color_10 = "#acc267"
g.terminal_color_11 = "#ddb26f"
g.terminal_color_12 = "#6fc2ef"
g.terminal_color_13 = "#e1a3ee"
g.terminal_color_14 = "#12cfc0"
g.terminal_color_15 = "#f5f5f5"
