-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "duskfly"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "MoonflySky" })
hi(0, "@attribute.bind.html", { link = "MoonflySky" })
hi(0, "@attribute.directive.value.html", { link = "MoonflyLavender" })
hi(0, "@attribute.on.html", { link = "MoonflyEmerald" })
hi(0, "@attribute.zig", { link = "MoonflyViolet" })
hi(0, "@character.special.vim", { link = "MoonflySky" })
hi(0, "@comment.error", { link = "MoonflyRed" })
hi(0, "@comment.note", { link = "MoonflyGrey58" })
hi(0, "@comment.ok", { link = "MoonflyGreen" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "MoonflyYellow" })
hi(0, "@conditional", { link = "@keyword.conditional" })
hi(0, "@constant", { link = "MoonflyTurquoise" })
hi(0, "@constant.builtin", { link = "MoonflyGreen" })
hi(0, "@constant.macro", { link = "MoonflyViolet" })
hi(0, "@constructor", { link = "MoonflyEmerald" })
hi(0, "@define", { link = "@keyword.directive.define" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@error", { link = "MoonflyRed" })
hi(0, "@exception", { link = "@keyword.exception" })
hi(0, "@field", { link = "@variable.member" })
hi(0, "@field.yaml", { link = "@variable.member.yaml" })
hi(0, "@function.builtin", { link = "Function" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "MoonflyTurquoise" })
hi(0, "@function.macro.vim", { link = "MoonflySky" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@include", { link = "@keyword.import" })
hi(0, "@include.rust", { link = "@keyword.import.rust" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "MoonflyViolet" })
hi(0, "@keyword.gitcommit", { link = "MoonflySky" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.import.bash", { link = "@keyword" })
hi(0, "@keyword.import.rust", { link = "@keyword" })
hi(0, "@keyword.operator", { link = "MoonflyViolet" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@keyword.storage.rust", { link = "MoonflyViolet" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.decorator.rust", { link = "@function.macro" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@storageclass" })
hi(0, "@lsp.type.macro", {})
hi(0, "@lsp.type.magicFunction", { link = "@function" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.namespace.ruby", {})
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", {})
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.parameter.dockerfile", { link = "@property" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#ff5454", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.dockerfile", { link = "@function" })
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@markup.environment", { link = "MoonflyViolet" })
hi(0, "@markup.environment.name", { link = "MoonflyEmerald" })
hi(0, "@markup.heading", { link = "MoonflyViolet" })
hi(0, "@markup.heading.1.markdown", { link = "MoonflyEmerald" })
hi(0, "@markup.heading.1.vimdoc", { link = "MoonflyBlue" })
hi(0, "@markup.heading.2.markdown", { link = "MoonflyLavender" })
hi(0, "@markup.heading.2.vimdoc", { link = "MoonflyBlue" })
hi(0, "@markup.heading.3.markdown", { link = "MoonflyTurquoise" })
hi(0, "@markup.heading.4.markdown", { link = "MoonflyOrange" })
hi(0, "@markup.heading.5.markdown", { link = "MoonflySky" })
hi(0, "@markup.heading.6.markdown", { link = "MoonflyViolet" })
hi(0, "@markup.heading.help", { link = "MoonflySky" })
hi(0, "@markup.heading.markdown", { link = "MoonflySky" })
hi(0, "@markup.italic", { fg = "#d99d93", italic = true })
hi(0, "@markup.link", { link = "MoonflyGreen" })
hi(0, "@markup.link.gitcommit", { link = "MoonflyBlue" })
hi(0, "@markup.link.label", { link = "MoonflyGreen" })
hi(0, "@markup.link.markdown_inline", {})
hi(0, "@markup.link.url", { fg = "#c67ddc", sp = "#808080", underline = true })
hi(0, "@markup.link.url.astro", { fg = "#db87c5", italic = true })
hi(0, "@markup.link.url.gitcommit", { link = "MoonflyEmerald" })
hi(0, "@markup.link.url.html", { fg = "#db87c5", italic = true })
hi(0, "@markup.link.url.svelte", { fg = "#db87c5", italic = true })
hi(0, "@markup.link.url.vue", { fg = "#db87c5", italic = true })
hi(0, "@markup.list", { link = "MoonflyCranberry" })
hi(0, "@markup.list.checked", { link = "MoonflyTurquoise" })
hi(0, "@markup.list.latex", { link = "MoonflyPurple" })
hi(0, "@markup.list.unchecked", { link = "MoonflyBlue" })
hi(0, "@markup.math", { link = "MoonflySky" })
hi(0, "@markup.quote", { link = "MoonflyGrey58" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.vimdoc", { link = "MoonflyOrchid" })
hi(0, "@markup.strong", { link = "MoonflyOrchid" })
hi(0, "@method", { link = "@function.method" })
hi(0, "@module", { link = "MoonflyTurquoise" })
hi(0, "@module.builtin", { link = "MoonflyGreen" })
hi(0, "@namespace", { link = "@module" })
hi(0, "@namespace.builtin", { link = "@module.builtin" })
hi(0, "@namespace.latex", { link = "MoonflyLavender" })
hi(0, "@parameter", { link = "@variable.parameter" })
hi(0, "@parameter.bash", { link = "@variable.parameter.bash" })
hi(0, "@parameter.builtin", { link = "MoonflyOrchid" })
hi(0, "@preproc", { link = "@keyword.directive" })
hi(0, "@property", { link = "MoonflyLavender" })
hi(0, "@punctuation.delimiter.astro", { link = "MoonflyCranberry" })
hi(0, "@punctuation.delimiter.css", { link = "MoonflyCranberry" })
hi(0, "@punctuation.delimiter.rust", { link = "MoonflyCranberry" })
hi(0, "@punctuation.delimiter.scss", { link = "MoonflyCranberry" })
hi(0, "@punctuation.delimiter.yaml", { link = "MoonflyCranberry" })
hi(0, "@punctuation.special", { link = "@markup.list" })
hi(0, "@repeat", { link = "@keyword.repeat" })
hi(0, "@storageclass", { link = "@keyword.storage" })
hi(0, "@storageclass.rust", { link = "@keyword.storage.rust" })
hi(0, "@string.documentation", { link = "MoonflyTurquoise" })
hi(0, "@string.json", { link = "MoonflyLime" })
hi(0, "@string.regex", { link = "@string.regexp" })
hi(0, "@string.regexp", { link = "MoonflyTurquoise" })
hi(0, "@string.special.path", { link = "MoonflyOrchid" })
hi(0, "@string.special.symbol", { link = "MoonflyPurple" })
hi(0, "@string.special.url", { link = "MoonflyPurple" })
hi(0, "@symbol", { link = "@string.special.symbol" })
hi(0, "@tag", { link = "MoonflyBlue" })
hi(0, "@tag.attribute", { link = "MoonflyTurquoise" })
hi(0, "@tag.builtin", { link = "MoonflyBlue" })
hi(0, "@tag.delimiter", { link = "MoonflyGreen" })
hi(0, "@tag.javascript", { link = "@type" })
hi(0, "@tag.jsx", { link = "@type" })
hi(0, "@tag.tsx", { link = "@type" })
hi(0, "@tag.typescript", { link = "@type" })
hi(0, "@text.danger", { link = "@comment.error" })
hi(0, "@text.diff.add", { link = "@diff.plus" })
hi(0, "@text.diff.change", { link = "@diff.delta" })
hi(0, "@text.diff.delete", { link = "@diff.minus" })
hi(0, "@text.emphasis", { link = "@markup.italic" })
hi(0, "@text.environment", { link = "@markup.environment" })
hi(0, "@text.environment.name", { link = "@markup.environment.name" })
hi(0, "@text.literal", { link = "@markup.raw" })
hi(0, "@text.literal.block.vimdoc", { link = "@markup.raw.block.vimdoc" })
hi(0, "@text.literal.vimdoc", { link = "@markup.raw.vimdoc" })
hi(0, "@text.math", { link = "@markup.math" })
hi(0, "@text.note", { link = "@comment.note" })
hi(0, "@text.reference", { link = "@markup.link" })
hi(0, "@text.reference.gitcommit", { link = "@markup.link.gitcommit" })
hi(0, "@text.reference.markdown_inline", { link = "@markup.link.label" })
hi(0, "@text.strike", { link = "@markup.strikethrough" })
hi(0, "@text.strong", { link = "@markup.strong" })
hi(0, "@text.title", { link = "@markup.heading" })
hi(0, "@text.title.1.markdown", { link = "@markup.heading.1.markdown" })
hi(0, "@text.title.1.marker.markdown", { link = "@markup.list" })
hi(0, "@text.title.1.vimdoc", { link = "@markup.heading.1.vimdoc" })
hi(0, "@text.title.2.markdown", { link = "@markup.heading.2.markdown" })
hi(0, "@text.title.2.marker.markdown", { link = "@markup.list" })
hi(0, "@text.title.2.vimdoc", { link = "@markup.heading.2.vimdoc" })
hi(0, "@text.title.3.markdown", { link = "@markup.heading.3.markdown" })
hi(0, "@text.title.3.marker.markdown", { link = "@markup.list" })
hi(0, "@text.title.4.markdown", { link = "@markup.heading.4.markdown" })
hi(0, "@text.title.4.marker.markdown", { link = "@markup.list" })
hi(0, "@text.title.5.markdown", { link = "@markup.heading.5.markdown" })
hi(0, "@text.title.5.marker.markdown", { link = "@markup.list" })
hi(0, "@text.title.6.markdown", { link = "@markup.heading.6.markdown" })
hi(0, "@text.title.6.marker.markdown", { link = "@markup.list" })
hi(0, "@text.title.help", { link = "@markup.heading.help" })
hi(0, "@text.title.markdown", { link = "@markup.heading.markdown" })
hi(0, "@text.todo", { link = "@comment.todo" })
hi(0, "@text.underline", { link = "@markup.underline" })
hi(0, "@text.uri", { link = "@markup.link.url" })
hi(0, "@text.uri.astro", { link = "@markup.link.url.astro" })
hi(0, "@text.uri.gitcommit", { link = "@markup.link.url.gitcommit" })
hi(0, "@text.uri.html", { link = "@markup.link.url.html" })
hi(0, "@text.uri.svelte", { link = "@markup.link.url.svelte" })
hi(0, "@text.uri.vue", { link = "@markup.link.url.vue" })
hi(0, "@text.warning", { link = "@comment.warning" })
hi(0, "@type.builtin", { link = "MoonflyEmerald" })
hi(0, "@type.qualifier", { link = "MoonflyViolet" })
hi(0, "@variable", { link = "MoonflyWhite" })
hi(0, "@variable.builtin", { link = "MoonflyGreen" })
hi(0, "@variable.builtin.vim", { link = "MoonflyEmerald" })
hi(0, "@variable.member", { link = "MoonflyLavender" })
hi(0, "@variable.member.ruby", { link = "MoonflyTurquoise" })
hi(0, "@variable.member.yaml", { link = "MoonflyBlue" })
hi(0, "@variable.parameter", { link = "MoonflyOrchid" })
hi(0, "@variable.parameter.bash", { link = "MoonflyTurquoise" })
hi(0, "@variable.scss", { link = "MoonflyTurquoise" })
hi(0, "@variable.vim", { link = "MoonflyTurquoise" })
hi(0, "ActionPreviewTitle", { link = "MoonflyBlue" })
hi(0, "Added", { ctermfg = 10, fg = "#d2eeb8" })
hi(0, "ArrowCurrentFile", { link = "MoonflyEmerald" })
hi(0, "BlinkCmpDocCursorLine", { link = "MoonflyCurrentLine" })
hi(0, "BlinkCmpKind", { link = "MoonflyWhite" })
hi(0, "BlinkCmpKindClass", { link = "MoonflyEmerald" })
hi(0, "BlinkCmpKindColor", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindConstant", { link = "MoonflyPurple" })
hi(0, "BlinkCmpKindConstructor", { link = "MoonflySky" })
hi(0, "BlinkCmpKindEnum", { link = "MoonflyViolet" })
hi(0, "BlinkCmpKindEnumMember", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindEvent", { link = "MoonflyViolet" })
hi(0, "BlinkCmpKindField", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindFile", { link = "MoonflyBlue" })
hi(0, "BlinkCmpKindFolder", { link = "MoonflyBlue" })
hi(0, "BlinkCmpKindFunction", { link = "MoonflySky" })
hi(0, "BlinkCmpKindInterface", { link = "MoonflyEmerald" })
hi(0, "BlinkCmpKindKeyword", { link = "MoonflyViolet" })
hi(0, "BlinkCmpKindMethod", { link = "MoonflySky" })
hi(0, "BlinkCmpKindModule", { link = "MoonflyEmerald" })
hi(0, "BlinkCmpKindOperator", { link = "MoonflyViolet" })
hi(0, "BlinkCmpKindProperty", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindReference", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindSnippet", { link = "MoonflyGreen" })
hi(0, "BlinkCmpKindStruct", { link = "MoonflyEmerald" })
hi(0, "BlinkCmpKindText", { link = "MoonflyGrey70" })
hi(0, "BlinkCmpKindTypeParameter", { link = "MoonflyEmerald" })
hi(0, "BlinkCmpKindUnit", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindValue", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpKindVariable", { link = "MoonflyTurquoise" })
hi(0, "BlinkCmpLabel", { link = "MoonflyWhite" })
hi(0, "BlinkCmpLabelMatch", { link = "CmpItemAbbrMatch" })
hi(0, "BlinkCmpMenu", { link = "NormalFloat" })
hi(0, "BlinkCmpMenuBorder", { link = "FloatBorder" })
hi(0, "BlinkCmpMenuSelection", { link = "PmenuSel" })
hi(0, "Boolean", { link = "MoonflyCranberry" })
hi(0, "BufferAlternate", { link = "BufferCurrent" })
hi(0, "BufferAlternateERROR", { link = "BufferCurrentERROR" })
hi(0, "BufferAlternateHINT", { link = "BufferCurrentHINT" })
hi(0, "BufferAlternateINFO", { link = "BufferCurrentINFO" })
hi(0, "BufferAlternateIndex", { link = "BufferCurrentIndex" })
hi(0, "BufferAlternateMod", { link = "BufferCurrentMod" })
hi(0, "BufferAlternateSign", { link = "BufferCurrentSign" })
hi(0, "BufferAlternateWARN", { link = "BufferCurrentWARN" })
hi(0, "BufferCurrent", { link = "MoonflyWhiteLineActive" })
hi(0, "BufferCurrentERROR", { link = "MoonflyRedLineActive" })
hi(0, "BufferCurrentHINT", { link = "MoonflyTurquoiseLineActive" })
hi(0, "BufferCurrentINFO", { link = "MoonflyBlueLineActive" })
hi(0, "BufferCurrentIndex", { link = "MoonflyWhiteLineActive" })
hi(0, "BufferCurrentMod", { link = "MoonflyYellowLineActive" })
hi(0, "BufferCurrentSign", { link = "MoonflyBlueLineActive" })
hi(0, "BufferCurrentWARN", { link = "MoonflyYellowLineActive" })
hi(0, "BufferInactive", { bg = "#2e2e2e", fg = "#949494" })
hi(0, "BufferInactiveERROR", { bg = "#2e2e2e", fg = "#ee6d29" })
hi(0, "BufferInactiveHINT", { bg = "#2e2e2e", fg = "#99d5b4" })
hi(0, "BufferInactiveINFO", { link = "BufferTabpages" })
hi(0, "BufferInactiveMod", { bg = "#2e2e2e", fg = "#dcca98" })
hi(0, "BufferInactiveSign", { bg = "#2e2e2e", fg = "#9e9e9e" })
hi(0, "BufferInactiveWARN", { bg = "#2e2e2e", fg = "#dcca98" })
hi(0, "BufferLineIndicatorSelected", { fg = "#60abf1" })
hi(0, "BufferLineTabSelected", { fg = "#60abf1" })
hi(0, "BufferTabpages", { bg = "#2e2e2e", fg = "#60abf1" })
hi(0, "BufferVisible", { link = "MoonflyGrey58Line" })
hi(0, "BufferVisibleERROR", { link = "GitSignsDeleteCul" })
hi(0, "BufferVisibleHINT", { bg = "#1c1c1c", fg = "#99d5b4" })
hi(0, "BufferVisibleINFO", { bg = "#1c1c1c", fg = "#60abf1" })
hi(0, "BufferVisibleIndex", { link = "MoonflyGrey58Line" })
hi(0, "BufferVisibleMod", { link = "MoonflyYellowLine" })
hi(0, "BufferVisibleSign", { link = "MoonflyGrey58Line" })
hi(0, "BufferVisibleWARN", { bg = "#1c1c1c", fg = "#dcca98" })
hi(0, "CallHierarchyIcon", { link = "MoonflyViolet" })
hi(0, "CallHierarchyTitle", { link = "MoonflyCranberry" })
hi(0, "Changed", { ctermfg = 14, fg = "#a4f6df" })
hi(0, "Character", { link = "MoonflyPurple" })
hi(0, "Cheat40Header", { link = "MoonflyBlue" })
hi(0, "CleverFDefaultLabel", { link = "MoonflyCrimson" })
hi(0, "CmpItemAbbrDefault", { fg = "#c6c6c6" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#949494" })
hi(0, "CmpItemAbbrMatch", { link = "MoonflyYellow" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c6c6c6" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "MoonflyCoral" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c6c6c6" })
hi(0, "CmpItemKind", { link = "MoonflyWhite" })
hi(0, "CmpItemKindClass", { link = "MoonflyEmerald" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "MoonflyPurple" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "MoonflySky" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnum", { link = "MoonflyViolet" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "MoonflyViolet" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "MoonflyBlue" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "MoonflyBlue" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "MoonflySky" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "MoonflyEmerald" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "MoonflyViolet" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "MoonflySky" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "MoonflyEmerald" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "MoonflyViolet" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "MoonflyGreen" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "MoonflyEmerald" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "MoonflyGrey70" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "MoonflyEmerald" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "MoonflyTurquoise" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { link = "MoonflyGrey39" })
hi(0, "CmpItemMenuDefault", { fg = "#c6c6c6" })
hi(0, "CocInlayHint", { link = "LspInlayHint" })
hi(0, "CocSemTypeBuiltin", { link = "MoonflyCranberry" })
hi(0, "CocSemTypeClass", { link = "MoonflyEmerald" })
hi(0, "CocSemTypeEnumMember", { link = "MoonflyTurquoise" })
hi(0, "CocSemTypeNamespace", { link = "MoonflyTurquoise" })
hi(0, "CocSemTypeParameter", { link = "MoonflyOrchid" })
hi(0, "CocSemTypeProperty", { link = "MoonflyLavender" })
hi(0, "CocSemTypeRegexp", { link = "MoonflyTurquoise" })
hi(0, "CocSemTypeStruct", { link = "MoonflyEmerald" })
hi(0, "CocSemTypeTypeParameter", { link = "MoonflyOrchid" })
hi(0, "CocUnusedHighlight", { link = "MoonflyGrey70" })
hi(0, "CodeActionConceal", { link = "MoonflyGreen" })
hi(0, "CodeActionText", { link = "MoonflyYellow" })
hi(0, "ColorColumn", { bg = "#121212" })
hi(0, "Comment", { fg = "#949494", italic = true })
hi(0, "Conceal", { fg = "#b2b2b2" })
hi(0, "Constant", { link = "MoonflyOrange" })
hi(0, "CtrlPMatch", { link = "MoonflyCoral" })
hi(0, "CurSearch", { bg = "#f09479", fg = "#080808" })
hi(0, "Cursor", { bg = "#9e9e9e", fg = "#080808" })
hi(0, "CursorColumn", { bg = "#1c1c1c" })
hi(0, "CursorLine", { bg = "#1c1c1c" })
hi(0, "CursorLineNr", { bg = "#1c1c1c", fg = "#60abf1" })
hi(0, "DapUIBreakpointsCurrentLine", { bg = "#1c1c1c", fg = "#b4bc4f" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "MoonflySky" })
hi(0, "DapUIBreakpointsPath", { link = "MoonflyTurquoise" })
hi(0, "DapUIDecoration", { link = "MoonflyBlue" })
hi(0, "DapUIFloatBorder", { link = "FloatBorder" })
hi(0, "DapUILineNumber", { link = "Number" })
hi(0, "DapUIModifiedValue", { fg = "#c6c6c6", underline = true })
hi(0, "DapUIPlayPause", { bg = "#262626", fg = "#b4bc4f" })
hi(0, "DapUIRestart", { link = "DapUIPlayPause" })
hi(0, "DapUIScope", { link = "MoonflySky" })
hi(0, "DapUISource", { link = "MoonflyViolet" })
hi(0, "DapUIStepBack", { bg = "#262626", fg = "#99d5b4" })
hi(0, "DapUIStepInto", { link = "DapUIStepBack" })
hi(0, "DapUIStepOut", { link = "DapUIStepBack" })
hi(0, "DapUIStepOver", { link = "DapUIStepBack" })
hi(0, "DapUIStop", { bg = "#262626", fg = "#ee6d29" })
hi(0, "DapUIStoppedThread", { link = "MoonflyTurquoise" })
hi(0, "DapUIThread", { link = "MoonflyGreen" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { bg = "#262626", fg = "#626262" })
hi(0, "DapUIWatchesEmpty", { link = "MoonflyRed" })
hi(0, "DapUIWatchesError", { link = "MoonflyRed" })
hi(0, "DapUIWatchesValue", { link = "MoonflyGreen" })
hi(0, "DapUIWinSelect", { link = "MoonflyBlue" })
hi(0, "DashboardCenter", { link = "MoonflyViolet" })
hi(0, "DashboardFooter", { link = "MoonflyCoral" })
hi(0, "DashboardHeader", { link = "MoonflyBlue" })
hi(0, "DashboardShortCut", { link = "MoonflyTurquoise" })
hi(0, "Delimiter", { link = "MoonflyWhite" })
hi(0, "DiagnosticError", { link = "MoonflyRed" })
hi(0, "DiagnosticFloatingError", { link = "MoonflyRed" })
hi(0, "DiagnosticFloatingHint", { link = "MoonflyTurquoise" })
hi(0, "DiagnosticFloatingInfo", { link = "MoonflySky" })
hi(0, "DiagnosticFloatingOk", { link = "MoonflyEmerald" })
hi(0, "DiagnosticFloatingWarn", { link = "MoonflyYellow" })
hi(0, "DiagnosticHint", { link = "MoonflyTurquoise" })
hi(0, "DiagnosticInfo", { link = "MoonflySky" })
hi(0, "DiagnosticOk", { link = "MoonflyEmerald" })
hi(0, "DiagnosticSignError", { link = "MoonflyRed" })
hi(0, "DiagnosticSignHint", { link = "MoonflyTurquoise" })
hi(0, "DiagnosticSignInfo", { link = "MoonflySky" })
hi(0, "DiagnosticSignOk", { link = "MoonflyEmerald" })
hi(0, "DiagnosticSignWarn", { link = "MoonflyYellow" })
hi(0, "DiagnosticSource", { link = "MoonflyGrey39" })
hi(0, "DiagnosticText", { link = "MoonflyRed" })
hi(0, "DiagnosticUnderlineError", { sp = "#ff5454", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#79dac8", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#74b2ff", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#36c692", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e3c78a", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { link = "MoonflyGrey39" })
hi(0, "DiagnosticVirtualTextHint", { link = "MoonflyGrey39" })
hi(0, "DiagnosticVirtualTextInfo", { link = "MoonflyGrey39" })
hi(0, "DiagnosticVirtualTextOk", { link = "MoonflyGrey39" })
hi(0, "DiagnosticVirtualTextWarn", { link = "MoonflyGrey39" })
hi(0, "DiagnosticWarn", { link = "MoonflyYellow" })
hi(0, "DiffAdd", { bg = "#314940" })
hi(0, "DiffChange", { bg = "#2e2e2e" })
hi(0, "DiffDelete", { bg = "#2e2e2e", fg = "#626262" })
hi(0, "DiffText", { bg = "#4d5d8d" })
hi(0, "Directory", { link = "MoonflyBlue" })
hi(0, "Error", { bg = "#080808", fg = "#ee6d29" })
hi(0, "ErrorMsg", { bg = "#080808", fg = "#ee6d29" })
hi(0, "Exception", { link = "MoonflyCrimson" })
hi(0, "FernBranchSymbol", { link = "MoonflyGrey58" })
hi(0, "FernBranchText", { link = "MoonflyBlue" })
hi(0, "FernGitStatusBracket", { link = "MoonflyGrey58" })
hi(0, "FernGitStatusIndex", { link = "MoonflyEmerald" })
hi(0, "FernGitStatusWorktree", { link = "MoonflyCrimson" })
hi(0, "FernLeaderSymbol", { link = "MoonflyGrey23" })
hi(0, "FernLeafSymbol", { link = "MoonflyBlue" })
hi(0, "FernMarkedLine", { link = "MoonflyVisual" })
hi(0, "FernMarkedText", { link = "MoonflyCrimson" })
hi(0, "FernRootSymbol", { link = "MoonflyPurple" })
hi(0, "FernRootText", { link = "MoonflyPurple" })
hi(0, "FinderCode", { link = "MoonflyWhite" })
hi(0, "FinderFName", { link = "MoonflyWhite" })
hi(0, "FinderIcon", { link = "MoonflyTurquoise" })
hi(0, "FinderSelection", { link = "MoonflyTurquoise" })
hi(0, "FinderSpinner", { link = "MoonflyPurple" })
hi(0, "FinderSpinnerTitle", { link = "MoonflyPurple" })
hi(0, "FinderType", { link = "MoonflyViolet" })
hi(0, "FloatBorder", { bg = "#080808", fg = "#2e2e2e" })
hi(0, "FloatTitle", { bg = "#3a3a3a", fg = "#c6c6c6" })
hi(0, "FoldColumn", { bg = "#2e2e2e", fg = "#b3d173" })
hi(0, "Folded", { bg = "#1c1c1c", fg = "#b3d173" })
hi(0, "Function", { link = "MoonflySky" })
hi(0, "FzfBorder", { fg = "#2e2e2e" })
hi(0, "FzfFgPlus", { fg = "#e4e4e4" })
hi(0, "FzfLuaBorder", { link = "FloatBorder" })
hi(0, "FzfLuaBufFlagAlt", { link = "MoonflyTurquoise" })
hi(0, "FzfLuaBufFlagCur", { link = "MoonflyOrange" })
hi(0, "FzfLuaBufNr", { link = "MoonflyKhaki" })
hi(0, "FzfLuaFzfHeader", { link = "MoonflyBlue" })
hi(0, "FzfLuaFzfInfo", { link = "String" })
hi(0, "FzfLuaFzfMarker", { link = "MoonflyCoral" })
hi(0, "FzfLuaFzfPointer", { link = "MoonflyCrimson" })
hi(0, "FzfLuaFzfPrompt", { link = "MoonflyBlue" })
hi(0, "FzfLuaFzfSpinner", { link = "MoonflyEmerald" })
hi(0, "FzfLuaHeaderBind", { link = "MoonflyGreen" })
hi(0, "FzfLuaHeaderText", { link = "MoonflyTurquoise" })
hi(0, "FzfLuaLiveSym", { link = "MoonflyGreen" })
hi(0, "FzfLuaPathColNr", { link = "MoonflySky" })
hi(0, "FzfLuaTabMarker", { link = "MoonflyKhaki" })
hi(0, "FzfLuaTabTitle", { link = "MoonflySky" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "FzfNormal", { fg = "#b2b2b2" })
hi(0, "FzfPrompt", { bg = "#2e2e2e", fg = "#60abf1" })
hi(0, "FzfSubstring", { fg = "#e0a06f" })
hi(0, "GitSignsAdd", { link = "MoonflyEmerald" })
hi(0, "GitSignsAddCul", { link = "TablineSelSymbol" })
hi(0, "GitSignsAddInline", { bg = "#8cc85f", fg = "#080808" })
hi(0, "GitSignsAddLn", { link = "MoonflyCurrentLine" })
hi(0, "GitSignsAddLnInline", { bg = "#373c4d" })
hi(0, "GitSignsAddPreview", { link = "MoonflyEmeraldLine" })
hi(0, "GitSignsChange", { link = "MoonflySky" })
hi(0, "GitSignsChangeCul", { bg = "#1c1c1c", fg = "#5dbaec" })
hi(0, "GitSignsChangeInline", { bg = "#e3c78a", fg = "#080808" })
hi(0, "GitSignsChangeLn", { bg = "#1c1c1c" })
hi(0, "GitSignsChangeLnInline", { bg = "#373c4d" })
hi(0, "GitSignsChangedelete", { link = "MoonflyCoral" })
hi(0, "GitSignsChangedeleteCul", { bg = "#1c1c1c", fg = "#e0a06f" })
hi(0, "GitSignsDelete", { link = "MoonflyRed" })
hi(0, "GitSignsDeleteCul", { bg = "#1c1c1c", fg = "#ee6d29" })
hi(0, "GitSignsDeleteInline", { bg = "#ff5454", fg = "#080808" })
hi(0, "GitSignsDeletePreview", { link = "MoonflyCrimsonLine" })
hi(0, "GitSignsDeleteVirtLn", { link = "MoonflyCrimsonLine" })
hi(0, "GitSignsStagedAdd", { fg = "#3c5f3d" })
hi(0, "GitSignsStagedAddCul", { bg = "#1c1c1c", fg = "#3c5f3d" })
hi(0, "GitSignsStagedAddLn", { bg = "#262626" })
hi(0, "GitSignsStagedAddNr", { fg = "#3c5f3d" })
hi(0, "GitSignsStagedChange", { fg = "#315d76" })
hi(0, "GitSignsStagedChangeCul", { bg = "#1c1c1c", fg = "#315d76" })
hi(0, "GitSignsStagedChangeLn", { bg = "#1c1c1c" })
hi(0, "GitSignsStagedChangeNr", { fg = "#315d76" })
hi(0, "GitSignsStagedChangedelete", { fg = "#705038" })
hi(0, "GitSignsStagedChangedeleteCul", { bg = "#1c1c1c", fg = "#705038" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#1c1c1c" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#315d76" })
hi(0, "GitSignsStagedDelete", { fg = "#793412" })
hi(0, "GitSignsStagedDeleteCul", { bg = "#1c1c1c", fg = "#793412" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#793412" })
hi(0, "GitSignsStagedTopdelete", { fg = "#793412" })
hi(0, "GitSignsStagedTopdeleteCul", { bg = "#1c1c1c", fg = "#793412" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#793412" })
hi(0, "GitSignsStagedUntracked", { fg = "#313131" })
hi(0, "GitSignsStagedUntrackedCul", { bg = "#1c1c1c", fg = "#313131" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#262626" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#3c5f3d" })
hi(0, "GitSignsTopdelete", { link = "MoonflyRed" })
hi(0, "GitSignsUntracked", { link = "MoonflyGrey39" })
hi(0, "GitSignsUntrackedCul", { bg = "#1c1c1c", fg = "#626262" })
hi(0, "GlyphPalette1", { link = "MoonflyCranberry" })
hi(0, "GlyphPalette2", { link = "MoonflyEmerald" })
hi(0, "GlyphPalette3", { link = "MoonflyYellow" })
hi(0, "GlyphPalette4", { link = "MoonflyBlue" })
hi(0, "GlyphPalette6", { link = "MoonflyTurquoise" })
hi(0, "GlyphPalette7", { link = "MoonflyWhite" })
hi(0, "GlyphPalette9", { link = "MoonflyCrimson" })
hi(0, "HopCursor", { link = "IncSearch" })
hi(0, "HopNextKey", { link = "MoonflyYellow" })
hi(0, "HopNextKey1", { link = "MoonflyBlue" })
hi(0, "HopNextKey2", { link = "MoonflyCrimson" })
hi(0, "HopUnmatched", { link = "MoonflyGrey62" })
hi(0, "IblIndent", { fg = "#262626", nocombine = true })
hi(0, "IblScope", { fg = "#db87c5", nocombine = true })
hi(0, "IblWhitespace", { fg = "#262626", nocombine = true })
hi(0, "Identifier", { link = "MoonflyTurquoise" })
hi(0, "Ignore", { link = "MoonflySky" })
hi(0, "IncSearch", { bg = "#e3c78a", fg = "#080808" })
hi(0, "Label", { link = "MoonflyTurquoise" })
hi(0, "LazyButton", { bg = "#262626", fg = "#c6c6c6" })
hi(0, "LazyButtonActive", { bg = "#4e4e4e", fg = "#e4e4e4" })
hi(0, "LazyCommit", { link = "MoonflyEmerald" })
hi(0, "LazyCommitType", { link = "MoonflyViolet" })
hi(0, "LazyDimmed", { fg = "#949494" })
hi(0, "LazyH1", { link = "MoonflyBlueMode" })
hi(0, "LazyNormal", { bg = "#121212", fg = "#c6c6c6" })
hi(0, "LazyProgressDone", { link = "MoonflyBlue" })
hi(0, "LazyProgressTodo", { link = "MoonflyGrey0" })
hi(0, "LazyReasonCmd", { link = "MoonflyGreen" })
hi(0, "LazyReasonPlugin", { link = "MoonflyOrchid" })
hi(0, "LazyReasonRuntime", { link = "MoonflyViolet" })
hi(0, "LazySpecial", { link = "MoonflyBlue" })
hi(0, "LineNr", { bg = "#080808", fg = "#626262" })
hi(0, "LineflyCommand", { link = "MoonflyYellowMode" })
hi(0, "LineflyInsert", { link = "MoonflyEmeraldMode" })
hi(0, "LineflyNormal", { link = "MoonflyBlueMode" })
hi(0, "LineflyReplace", { link = "MoonflyCrimsonMode" })
hi(0, "LineflyVisual", { link = "MoonflyPurpleMode" })
hi(0, "LspCodeLens", { link = "MoonflyGrey39" })
hi(0, "LspCodeLensSeparator", { link = "MoonflyGrey39" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#1c1c1c", fg = "#949494" })
hi(0, "LspReferenceRead", { link = "MoonflyVisual" })
hi(0, "LspReferenceText", { link = "MoonflyVisual" })
hi(0, "LspReferenceWrite", { link = "MoonflyVisual" })
hi(0, "LspSignatureActiveParameter", { bg = "#2e2e2e" })
hi(0, "MasonError", { link = "MoonflyRed" })
hi(0, "MasonHeader", { link = "MoonflyBlueMode" })
hi(0, "MasonHeaderSecondary", { link = "MoonflyBlueMode" })
hi(0, "MasonHeading", { link = "MoonflyGrey89" })
hi(0, "MasonHighlight", { link = "MoonflyBlue" })
hi(0, "MasonHighlightBlock", { link = "MoonflyBlueMode" })
hi(0, "MasonHighlightBlockBold", { link = "MoonflyBlueMode" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MoonflyEmeraldMode" })
hi(0, "MasonHighlightBlockSecondary", { link = "MoonflyEmeraldMode" })
hi(0, "MasonHighlightSecondary", { link = "MoonflyEmerald" })
hi(0, "MasonLink", { link = "MoonflyPurple" })
hi(0, "MasonMuted", { link = "MoonflyGrey39" })
hi(0, "MasonMutedBlock", { bg = "#262626", fg = "#c6c6c6" })
hi(0, "MasonMutedBlockBold", { bg = "#262626", fg = "#e4e4e4" })
hi(0, "MatchParen", { link = "MoonflyVisual" })
hi(0, "MatchWord", { link = "MoonflyCoral" })
hi(0, "MatchWordCur", { bg = "#080808" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { link = "MoonflyVisual" })
hi(0, "MiniCursorword", { link = "MoonflyUnderline" })
hi(0, "MiniCursorwordCurrent", { link = "MoonflyUnderline" })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "MoonflyCrimsonLine" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "MoonflyCrimsonLine" })
hi(0, "MiniDiffSignAdd", { link = "MoonflyEmerald" })
hi(0, "MiniDiffSignChange", { link = "MoonflySky" })
hi(0, "MiniDiffSignDelete", { link = "MoonflyRed" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "MoonflyCurrentLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { link = "MoonflyWhite" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { link = "MoonflyEmeraldLine" })
hi(0, "MiniHipatternsFixme", { bg = "#ff5454", fg = "#080808" })
hi(0, "MiniHipatternsHack", { bg = "#e3c78a", fg = "#080808" })
hi(0, "MiniHipatternsNote", { bg = "#74b2ff", fg = "#080808" })
hi(0, "MiniHipatternsTodo", { bg = "#79dac8", fg = "#080808" })
hi(0, "MiniIconsAzure", { link = "MoonflySky" })
hi(0, "MiniIconsBlue", { link = "MoonflyBlue" })
hi(0, "MiniIconsCyan", { link = "MoonflyTurquoise" })
hi(0, "MiniIconsGreen", { link = "MoonflyGreen" })
hi(0, "MiniIconsGrey", { link = "MoonflyGrey89" })
hi(0, "MiniIconsOrange", { link = "MoonflyOrange" })
hi(0, "MiniIconsPurple", { link = "MoonflyPurple" })
hi(0, "MiniIconsRed", { link = "MoonflyCrimson" })
hi(0, "MiniIconsYellow", { link = "MoonflyYellow" })
hi(0, "MiniIndentscopePrefix", { link = "MoonflyNoCombine" })
hi(0, "MiniIndentscopeSymbol", { link = "MoonflyWhite" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "MoonflyGrey58" })
hi(0, "MiniJump2dSpot", { fg = "#dcca98", nocombine = true, underline = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#262626", fg = "#60abf1", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { fg = "#7bbd7a", nocombine = true, underline = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "MoonflyCurrentLine" })
hi(0, "MiniPickMatchMarked", { link = "DiffAdd" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniStarterCurrent", { link = "MoonflyNoCombine" })
hi(0, "MiniStarterHeader", { link = "MoonflyViolet" })
hi(0, "MiniStarterItemPrefix", { link = "MoonflyYellow" })
hi(0, "MiniStarterQuery", { link = "MoonflySky" })
hi(0, "MiniStarterSection", { link = "MoonflyCrimson" })
hi(0, "MiniStatuslineDevinfo", { bg = "#626262", fg = "#c6c6c6" })
hi(0, "MiniStatuslineFileinfo", { bg = "#626262", fg = "#c6c6c6" })
hi(0, "MiniStatuslineFilename", { bg = "#2e2e2e", fg = "#9e9e9e" })
hi(0, "MiniStatuslineInactive", { bg = "#2e2e2e", fg = "#9e9e9e" })
hi(0, "MiniStatuslineModeCommand", { link = "MoonflyYellowMode" })
hi(0, "MiniStatuslineModeInsert", { link = "MoonflyEmeraldMode" })
hi(0, "MiniStatuslineModeNormal", { link = "MoonflyBlueMode" })
hi(0, "MiniStatuslineModeOther", { link = "MoonflyTurquoiseMode" })
hi(0, "MiniStatuslineModeReplace", { link = "MoonflyCrimsonMode" })
hi(0, "MiniStatuslineModeVisual", { link = "MoonflyPurpleMode" })
hi(0, "MiniTablineCurrent", { link = "MoonflyWhiteLineActive" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#2e2e2e", fg = "#949494" })
hi(0, "MiniTablineModifiedCurrent", { link = "MoonflyYellowLineActive" })
hi(0, "MiniTablineModifiedHidden", { bg = "#2e2e2e", fg = "#dcca98" })
hi(0, "MiniTablineModifiedVisible", { link = "MoonflyYellowLine" })
hi(0, "MiniTablineTabpagesection", { link = "MoonflyBlueMode" })
hi(0, "MiniTablineVisible", { link = "MoonflyGrey58Line" })
hi(0, "MiniTestEmphasis", { link = "MoonflyUnderline" })
hi(0, "MiniTestFail", { link = "MoonflyRed" })
hi(0, "MiniTestPass", { link = "MoonflyGreen" })
hi(0, "MiniTrailspace", { link = "MoonflyCrimsonMode" })
hi(0, "ModeMsg", { fg = "#9e9e9e" })
hi(0, "MoonflyBlue", { fg = "#60abf1" })
hi(0, "MoonflyBlueLineActive", { bg = "#444444", fg = "#60abf1" })
hi(0, "MoonflyBlueMode", { bg = "#80a0ff", fg = "#1c1c1c" })
hi(0, "MoonflyCoral", { fg = "#e0a06f" })
hi(0, "MoonflyCranberry", { fg = "#dc6d53" })
hi(0, "MoonflyCrimson", { fg = "#f6605b" })
hi(0, "MoonflyCrimsonLine", { bg = "#2e2e2e", fg = "#f6605b" })
hi(0, "MoonflyCrimsonMode", { bg = "#ff5189", fg = "#1c1c1c" })
hi(0, "MoonflyCurrentLine", { bg = "#262626" })
hi(0, "MoonflyEmerald", { fg = "#7bbd7a" })
hi(0, "MoonflyEmeraldLine", { bg = "#2e2e2e", fg = "#7bbd7a" })
hi(0, "MoonflyEmeraldMode", { bg = "#36c692", fg = "#1c1c1c" })
hi(0, "MoonflyGreen", { fg = "#b4bc4f" })
hi(0, "MoonflyGrey0", { fg = "#343434" })
hi(0, "MoonflyGrey15", { fg = "#262626" })
hi(0, "MoonflyGrey18", { fg = "#2e2e2e" })
hi(0, "MoonflyGrey23", { fg = "#3a3a3a" })
hi(0, "MoonflyGrey27", { fg = "#444444" })
hi(0, "MoonflyGrey30", { fg = "#4e4e4e" })
hi(0, "MoonflyGrey39", { fg = "#626262" })
hi(0, "MoonflyGrey58", { fg = "#949494" })
hi(0, "MoonflyGrey58Line", { bg = "#1c1c1c", fg = "#949494" })
hi(0, "MoonflyGrey62", { fg = "#9e9e9e" })
hi(0, "MoonflyGrey70", { fg = "#b2b2b2" })
hi(0, "MoonflyGrey89", { fg = "#e4e4e4" })
hi(0, "MoonflyKhaki", { fg = "#d3c08e" })
hi(0, "MoonflyLavender", { fg = "#c1a9e1" })
hi(0, "MoonflyLime", { fg = "#b3d173" })
hi(0, "MoonflyNoCombine", { nocombine = true })
hi(0, "MoonflyOrange", { fg = "#cc9e5e" })
hi(0, "MoonflyOrchid", { fg = "#d99d93" })
hi(0, "MoonflyPurple", { fg = "#c67ddc" })
hi(0, "MoonflyPurpleMode", { bg = "#ae81ff", fg = "#1c1c1c" })
hi(0, "MoonflyRed", { fg = "#ee6d29" })
hi(0, "MoonflyRedLineActive", { bg = "#444444", fg = "#ee6d29" })
hi(0, "MoonflySky", { fg = "#5dbaec" })
hi(0, "MoonflyTurquoise", { fg = "#99d5b4" })
hi(0, "MoonflyTurquoiseLineActive", { bg = "#444444", fg = "#99d5b4" })
hi(0, "MoonflyTurquoiseMode", { bg = "#79dac8", fg = "#1c1c1c" })
hi(0, "MoonflyUnderline", { underline = true })
hi(0, "MoonflyViolet", { fg = "#db87c5" })
hi(0, "MoonflyVisual", { bg = "#323437" })
hi(0, "MoonflyWhite", { fg = "#c6c6c6" })
hi(0, "MoonflyWhiteLineActive", { bg = "#444444", fg = "#e4e4e4" })
hi(0, "MoonflyYellow", { fg = "#dcca98" })
hi(0, "MoonflyYellowLine", { bg = "#1c1c1c", fg = "#dcca98" })
hi(0, "MoonflyYellowLineActive", { bg = "#444444", fg = "#dcca98" })
hi(0, "MoonflyYellowMode", { bg = "#e3c78a", fg = "#1c1c1c" })
hi(0, "MoreMsg", { fg = "#ee6d29" })
hi(0, "NavicIconsBoolean", { link = "NavicIconsOperator" })
hi(0, "NavicIconsClass", { bg = "#2e2e2e", fg = "#7bbd7a" })
hi(0, "NavicIconsConstant", { bg = "#2e2e2e", fg = "#cc9e5e" })
hi(0, "NavicIconsConstructor", { bg = "#2e2e2e", fg = "#5dbaec" })
hi(0, "NavicIconsEnum", { bg = "#2e2e2e", fg = "#db87c5" })
hi(0, "NavicIconsEnumMember", { bg = "#2e2e2e", fg = "#99d5b4" })
hi(0, "NavicIconsEvent", { link = "NavicIconsConstant" })
hi(0, "NavicIconsField", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsFile", { bg = "#2e2e2e", fg = "#60abf1" })
hi(0, "NavicIconsFunction", { link = "NavicIconsConstructor" })
hi(0, "NavicIconsInterface", { link = "NavicIconsEnum" })
hi(0, "NavicIconsKey", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsMethod", { link = "NavicIconsConstructor" })
hi(0, "NavicIconsModule", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsNamespace", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsNull", { bg = "#2e2e2e", fg = "#b4bc4f" })
hi(0, "NavicIconsNumber", { link = "NavicIconsConstant" })
hi(0, "NavicIconsObject", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsOperator", { bg = "#2e2e2e", fg = "#dc6d53" })
hi(0, "NavicIconsPackage", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsProperty", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsString", { bg = "#2e2e2e", fg = "#d3c08e" })
hi(0, "NavicIconsStruct", { link = "NavicIconsClass" })
hi(0, "NavicIconsTypeParameter", { link = "NavicIconsEnumMember" })
hi(0, "NavicIconsVariable", { link = "NavicIconsEnumMember" })
hi(0, "NavicSeparator", { bg = "#2e2e2e", fg = "#c6c6c6" })
hi(0, "NavicText", { bg = "#2e2e2e", fg = "#b2b2b2" })
hi(0, "NeoTreeCursorLine", { link = "MoonflyCurrentLine" })
hi(0, "NeoTreeDimText", { link = "MoonflyGrey30" })
hi(0, "NeoTreeDirectoryIcon", { link = "MoonflyGrey58" })
hi(0, "NeoTreeDotfile", { link = "MoonflyGrey58" })
hi(0, "NeoTreeFilterTerm", { link = "MoonflyBlue" })
hi(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
hi(0, "NeoTreeGitAdded", { link = "MoonflyGreen" })
hi(0, "NeoTreeGitConflict", { link = "MoonflyCrimson" })
hi(0, "NeoTreeGitModified", { link = "MoonflyTurquoise" })
hi(0, "NeoTreeGitUntracked", { link = "MoonflyOrchid" })
hi(0, "NeoTreeIndentMarker", { link = "MoonflyGrey23" })
hi(0, "NeoTreeMessage", { link = "MoonflyGrey62" })
hi(0, "NeoTreeModified", { link = "MoonflyYellow" })
hi(0, "NeoTreeRootName", { link = "MoonflyPurple" })
hi(0, "NeoTreeTitleBar", { bg = "#2e2e2e", fg = "#c6c6c6" })
hi(0, "NeogitBranch", { link = "MoonflySky" })
hi(0, "NeogitDiffAddHighlight", { link = "MoonflyEmeraldLine" })
hi(0, "NeogitDiffContextHighlight", { bg = "#1c1c1c" })
hi(0, "NeogitDiffDeleteHighlight", { link = "MoonflyCrimsonLine" })
hi(0, "NeogitHunkHeader", { link = "Pmenu" })
hi(0, "NeogitHunkHeaderHighlight", { link = "MoonflyBlueLineActive" })
hi(0, "NeogitRemote", { link = "MoonflyPurple" })
hi(0, "NoiceCmdlinePopup", { link = "MoonflyGrey50" })
hi(0, "NoiceCmdlinePopupBorder", { link = "MoonflyGrey27" })
hi(0, "NoiceCmdlinePopupBorderSearch", { link = "MoonflyGrey27" })
hi(0, "NoiceCmdlinePrompt", { link = "MoonflyBlue" })
hi(0, "NoiceCompletionItemKindDefault", { link = "MoonflyTurquoise" })
hi(0, "NoiceConfirmBorder", { link = "MoonflyBlue" })
hi(0, "NoiceFormatTitle", { link = "MoonflyCranberry" })
hi(0, "NonText", { fg = "#626262" })
hi(0, "Normal", { bg = "#080808", fg = "#c6c6c6" })
hi(0, "NormalFloat", { bg = "#1c1c1c", fg = "#c6c6c6" })
hi(0, "NotifyDEBUGBorder", { link = "FloatBorder" })
hi(0, "NotifyDEBUGIcon", { link = "MoonflyGrey58" })
hi(0, "NotifyDEBUGTitle", { link = "MoonflyGrey58" })
hi(0, "NotifyERRORBorder", { link = "FloatBorder" })
hi(0, "NotifyERRORIcon", { link = "MoonflyRed" })
hi(0, "NotifyERRORTitle", { link = "MoonflyRed" })
hi(0, "NotifyINFOBorder", { link = "FloatBorder" })
hi(0, "NotifyINFOIcon", { link = "MoonflyBlue" })
hi(0, "NotifyINFOTitle", { link = "MoonflyBlue" })
hi(0, "NotifyTRACEBorder", { link = "FloatBorder" })
hi(0, "NotifyTRACEIcon", { link = "MoonflyPurple" })
hi(0, "NotifyTRACETitle", { link = "MoonflyPurple" })
hi(0, "NotifyWARNBorder", { link = "FloatBorder" })
hi(0, "NotifyWARNIcon", { link = "MoonflyYellow" })
hi(0, "NotifyWARNTitle", { link = "MoonflyYellow" })
hi(0, "NvChAsciiHeader", { link = "Directory" })
hi(0, "NvChSection", { link = "Pmenu" })
hi(0, "NvCheatsheetBlue", { link = "MoonflyBlueMode" })
hi(0, "NvCheatsheetCyan", { link = "MoonflyTurquoiseMode" })
hi(0, "NvCheatsheetGray", { bg = "#e196a2", fg = "#1c1c1c" })
hi(0, "NvCheatsheetGreen", { link = "MoonflyEmeraldMode" })
hi(0, "NvCheatsheetMagenta", { bg = "#cf87e8", fg = "#1c1c1c" })
hi(0, "NvCheatsheetOrange", { bg = "#f09479", fg = "#1c1c1c" })
hi(0, "NvCheatsheetPurple", { link = "MoonflyPurpleMode" })
hi(0, "NvCheatsheetRed", { link = "MoonflyCrimsonMode" })
hi(0, "NvCheatsheetWhite", { bg = "#c6c6c6", fg = "#1c1c1c" })
hi(0, "NvCheatsheetYellow", { link = "MoonflyYellowMode" })
hi(0, "NvimInternalError", { bg = "#ff0000", ctermbg = 9, ctermfg = 9, fg = "#ce6824" })
hi(0, "NvimTreeCursorLine", { link = "MoonflyCurrentLine" })
hi(0, "NvimTreeExecFile", { fg = "#b4bc4f" })
hi(0, "NvimTreeFolderIcon", { link = "MoonflyGrey58" })
hi(0, "NvimTreeFolderName", { link = "MoonflyBlue" })
hi(0, "NvimTreeImageFile", { fg = "#db87c5" })
hi(0, "NvimTreeIndentMarker", { link = "MoonflyGrey23" })
hi(0, "NvimTreeNormalFloat", { bg = "#080808", fg = "#b2b2b2" })
hi(0, "NvimTreeOpenedFile", { fg = "#dcca98" })
hi(0, "NvimTreeOpenedFolderName", { link = "MoonflyBlue" })
hi(0, "NvimTreeRootFolder", { link = "MoonflyPurple" })
hi(0, "NvimTreeSpecialFile", { link = "MoonflyYellow" })
hi(0, "NvimTreeSymlink", { fg = "#99d5b4" })
hi(0, "NvimTreeWindowPicker", { link = "DiffChange" })
hi(0, "Operator", { link = "MoonflyCranberry" })
hi(0, "OutlineIndent", { link = "MoonflyPurple" })
hi(0, "Pmenu", { bg = "#262626", fg = "#c6c6c6" })
hi(0, "PmenuSbar", { link = "MoonflyCurrentLine" })
hi(0, "PmenuSel", { bg = "#4d5d8d", fg = "#e4e4e4" })
hi(0, "PmenuThumb", { bg = "#808080" })
hi(0, "PreProc", { link = "MoonflyCranberry" })
hi(0, "Question", { fg = "#b3d173" })
hi(0, "QuickFixLine", { link = "MoonflyCurrentLine" })
hi(0, "RainbowDelimiterBlue", { link = "MoonflyBlue" })
hi(0, "RainbowDelimiterCyan", { link = "MoonflyTurquoise" })
hi(0, "RainbowDelimiterGreen", { link = "MoonflyGreen" })
hi(0, "RainbowDelimiterOrange", { link = "MoonflyOrange" })
hi(0, "RainbowDelimiterRed", { link = "MoonflyRed" })
hi(0, "RainbowDelimiterViolet", { link = "MoonflyViolet" })
hi(0, "RainbowDelimiterYellow", { link = "MoonflyYellow" })
hi(0, "Removed", { ctermfg = 9, fg = "#f7c6af" })
hi(0, "RenameNormal", { link = "MoonflyOrange" })
hi(0, "Repeat", { link = "MoonflyViolet" })
hi(0, "SagaBeacon", { link = "MoonflyPurpleMode" })
hi(0, "SagaBorder", { link = "FloatBorder" })
hi(0, "SagaCollapse", { link = "MoonflyCranberry" })
hi(0, "SagaExpand", { link = "MoonflyCranberry" })
hi(0, "SagaNormal", { link = "Normal" })
hi(0, "SagaShadow", { link = "Normal" })
hi(0, "Search", { bg = "#373c4d", fg = "#e4e4e4" })
hi(0, "SignColumn", { bg = "#080808", fg = "#b3d173" })
hi(0, "SnacksBorderTitleDebug", { link = "FloatBorder" })
hi(0, "SnacksBorderTitleError", { link = "FloatBorder" })
hi(0, "SnacksBorderTitleInfo", { link = "FloatBorder" })
hi(0, "SnacksBorderTitleTrace", { link = "FloatBorder" })
hi(0, "SnacksBorderTitleWarn", { link = "FloatBorder" })
hi(0, "SnacksDashboardDesc", { link = "MoonflyTurquoise" })
hi(0, "SnacksDashboardDir", { link = "MoonflyEmerald" })
hi(0, "SnacksDashboardFile", { link = "MoonflyGreen" })
hi(0, "SnacksDashboardFooter", { link = "MoonflyBlue" })
hi(0, "SnacksDashboardHeader", { link = "MoonflyBlue" })
hi(0, "SnacksDashboardIcon", { link = "MoonflySky" })
hi(0, "SnacksDashboardSpecial", { link = "MoonflyViolet" })
hi(0, "SnacksNotifierDebug", { link = "DiagnosticHint" })
hi(0, "SnacksNotifierError", { link = "DiagnosticError" })
hi(0, "SnacksNotifierIconDebug", { link = "DiagnosticHint" })
hi(0, "SnacksNotifierIconError", { link = "DiagnosticError" })
hi(0, "SnacksNotifierIconInfo", { link = "DiagnosticInfo" })
hi(0, "SnacksNotifierIconTrace", { link = "DiagnosticHint" })
hi(0, "SnacksNotifierIconWarn", { link = "DiagnosticWarn" })
hi(0, "SnacksNotifierInfo", { link = "DiagnosticInfo" })
hi(0, "SnacksNotifierTitleDebug", { link = "DiagnosticHint" })
hi(0, "SnacksNotifierTitleError", { link = "DiagnosticError" })
hi(0, "SnacksNotifierTitleInfo", { link = "DiagnosticInfo" })
hi(0, "SnacksNotifierTitleTrace", { link = "DiagnosticHint" })
hi(0, "SnacksNotifierTitleWarn", { link = "DiagnosticWarn" })
hi(0, "SnacksNotifierTrace", { link = "DiagnosticHint" })
hi(0, "SnacksNotifierWarn", { link = "DiagnosticWarn" })
hi(0, "SnacksScratchKey", { link = "DiagnosticInfo" })
hi(0, "SnacksWinBar", { link = "MoonflyBlue" })
hi(0, "Special", { link = "MoonflyCranberry" })
hi(0, "SpecialKey", { bg = "#080808", fg = "#5dbaec" })
hi(0, "SpellBad", { sp = "#ff5454", undercurl = true })
hi(0, "SpellCap", { sp = "#e3c78a", undercurl = true })
hi(0, "SpellLocal", { sp = "#74b2ff", undercurl = true })
hi(0, "SpellRare", { sp = "#8cc85f", undercurl = true })
hi(0, "Statement", { fg = "#db87c5" })
hi(0, "StatusLine", { bg = "#2e2e2e", fg = "#c6c6c6" })
hi(0, "StatusLineNC", { bg = "#2e2e2e", fg = "#9e9e9e" })
hi(0, "StatusLineTerm", { bg = "#2e2e2e", fg = "#c6c6c6" })
hi(0, "StatusLineTermNC", { bg = "#2e2e2e", fg = "#9e9e9e" })
hi(0, "StorageClass", { link = "MoonflyViolet" })
hi(0, "String", { link = "MoonflyKhaki" })
hi(0, "Structure", { link = "MoonflyBlue" })
hi(0, "TabLine", { bg = "#2e2e2e", fg = "#9e9e9e" })
hi(0, "TabLineFill", { bg = "#2e2e2e", fg = "#2e2e2e" })
hi(0, "TabLineSel", { bg = "#1c1c1c", fg = "#60abf1" })
hi(0, "TablineSelSymbol", { bg = "#1c1c1c", fg = "#7bbd7a" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { link = "MoonflyCoral" })
hi(0, "TelescopeMultiIcon", { link = "MoonflyCrimson" })
hi(0, "TelescopeMultiSelection", { link = "MoonflyEmerald" })
hi(0, "TelescopeNormal", { link = "MoonflyGrey70" })
hi(0, "TelescopePreviewDate", { link = "MoonflyGrey58" })
hi(0, "TelescopePreviewGroup", { link = "MoonflyGrey58" })
hi(0, "TelescopePreviewLink", { link = "MoonflyTurquoise" })
hi(0, "TelescopePreviewMatch", { link = "MoonflyVisual" })
hi(0, "TelescopePreviewRead", { link = "MoonflyOrange" })
hi(0, "TelescopePreviewSize", { link = "MoonflyEmerald" })
hi(0, "TelescopePreviewUser", { link = "MoonflyGrey58" })
hi(0, "TelescopePromptPrefix", { link = "MoonflyBlue" })
hi(0, "TelescopeResultsDiffAdd", { link = "MoonflyGreen" })
hi(0, "TelescopeResultsDiffChange", { link = "MoonflyRed" })
hi(0, "TelescopeResultsDiffDelete", { link = "MoonflyCrimsonLine" })
hi(0, "TelescopeResultsSpecialComment", { link = "MoonflyGrey39" })
hi(0, "TelescopeSelection", { bg = "#323437", fg = "#e4e4e4" })
hi(0, "TelescopeSelectionCaret", { link = "MoonflyCrimson" })
hi(0, "TelescopeTitle", { link = "MoonflyGrey39" })
hi(0, "TermCursor", { bg = "#9e9e9e", fg = "#080808" })
hi(0, "Title", { fg = "#cc9e5e" })
hi(0, "TitleIcon", { link = "MoonflyBlue" })
hi(0, "TitleString", { link = "MoonflyBlue" })
hi(0, "TitleSymbol", { link = "MoonflyBlue" })
hi(0, "Todo", { bg = "#262626", fg = "#dcca98" })
hi(0, "TreesitterContext", { bg = "#121212" })
hi(0, "TreesitterContextBottom", { sp = "#2e2e2e", underline = true })
hi(0, "Type", { fg = "#7bbd7a" })
hi(0, "Underlined", { fg = "#7bbd7a" })
hi(0, "VertSplit", { bg = "#2e2e2e", fg = "#2e2e2e" })
hi(0, "Visual", { link = "MoonflyVisual" })
hi(0, "VisualNOS", { bg = "#323437", fg = "#c6c6c6" })
hi(0, "WarningMsg", { bg = "#080808", fg = "#cc9e5e" })
hi(0, "Whitespace", { fg = "#343434" })
hi(0, "WildMenu", { bg = "#4d5d8d", fg = "#e4e4e4" })
hi(0, "WinBar", { bg = "#262626", fg = "#c6c6c6" })
hi(0, "WinBarNC", { bg = "#262626", fg = "#9e9e9e" })
hi(0, "WinSeparator", { link = "VertSplit" })
hi(0, "WindowPickerStatusLine", { link = "WinBar" })
hi(0, "WindowPickerStatusLineNC", { link = "WinBar" })
hi(0, "WindowPickerWinBar", { link = "WinBar" })
hi(0, "WindowPickerWinBarNC", { link = "WinBar" })
hi(0, "bufExplorerHelp", { link = "MoonflyGrey62" })
hi(0, "bufExplorerSortBy", { link = "MoonflyGrey62" })
hi(0, "csvCol0", { link = "MoonflyRed" })
hi(0, "csvCol1", { link = "MoonflyOrange" })
hi(0, "csvCol2", { link = "MoonflyYellow" })
hi(0, "csvCol3", { link = "MoonflyGreen" })
hi(0, "csvCol4", { link = "MoonflyTurquoise" })
hi(0, "csvCol5", { link = "MoonflyBlue" })
hi(0, "csvCol6", { link = "MoonflyPurple" })
hi(0, "csvCol7", { link = "MoonflyViolet" })
hi(0, "csvCol8", { link = "MoonflyLavender" })
hi(0, "diffAdded", { link = "MoonflyGreen" })
hi(0, "diffChanged", { link = "MoonflyCrimson" })
hi(0, "diffIndexLine", { link = "MoonflyCrimson" })
hi(0, "diffLine", { link = "MoonflySky" })
hi(0, "diffRemoved", { link = "MoonflyRed" })
hi(0, "diffSubname", { link = "MoonflySky" })
hi(0, "fishInnerVariable", { link = "MoonflyTurquoise" })
hi(0, "fishParameter", { link = "MoonflyTurquoise" })
hi(0, "fishVariable", { link = "MoonflyTurquoise" })
hi(0, "gitCommitBranch", { link = "MoonflySky" })
hi(0, "gitCommitDiscardedFile", { link = "MoonflyCrimson" })
hi(0, "gitCommitDiscardedType", { link = "MoonflySky" })
hi(0, "gitCommitHeader", { link = "MoonflyPurple" })
hi(0, "gitCommitSelectedFile", { link = "MoonflyEmerald" })
hi(0, "gitCommitSelectedType", { link = "MoonflySky" })
hi(0, "gitCommitUntrackedFile", { link = "MoonflyCranberry" })
hi(0, "gitEmail", { link = "MoonflyBlue" })
hi(0, "healthHeadingChar", { link = "MoonflyBlue" })
hi(0, "healthSuccess", { link = "DiffAdd" })
hi(0, "helpCommand", { link = "MoonflyOrchid" })
hi(0, "helpExample", { link = "MoonflyGreen" })
hi(0, "helpHeader", { link = "MoonflyTurquoise" })
hi(0, "helpHeadline", { link = "MoonflyBlue" })
hi(0, "helpHyperTextEntry", { link = "MoonflyTurquoise" })
hi(0, "helpSectionDelim", { link = "MoonflyBlue" })
hi(0, "lCursor", { bg = "#9e9e9e", fg = "#080808" })
hi(0, "lualine_a_command", { bg = "#e3c78a", fg = "#1c1c1c" })
hi(0, "lualine_a_inactive", { bg = "#303030", fg = "#9e9e9e" })
hi(0, "lualine_a_insert", { bg = "#36c692", fg = "#1c1c1c" })
hi(0, "lualine_a_normal", { bg = "#80a0ff", fg = "#1c1c1c" })
hi(0, "lualine_a_replace", { bg = "#ff5189", fg = "#1c1c1c" })
hi(0, "lualine_a_terminal", { bg = "#36c692", fg = "#1c1c1c" })
hi(0, "lualine_a_visual", { bg = "#ae81ff", fg = "#1c1c1c" })
hi(0, "lualine_b_command", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_error_command", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_error_inactive", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_error_insert", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_error_normal", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_error_replace", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_error_terminal", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_error_visual", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diagnostics_hint_command", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_hint_inactive", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_hint_insert", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_hint_normal", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_hint_replace", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_hint_terminal", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_hint_visual", { bg = "#303030", fg = "#99d5b4" })
hi(0, "lualine_b_diagnostics_info_command", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_info_inactive", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_info_insert", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_info_normal", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_info_replace", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_info_terminal", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_info_visual", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diagnostics_warn_command", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_warn_inactive", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_warn_insert", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_warn_normal", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_warn_replace", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_warn_terminal", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diagnostics_warn_visual", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_b_diff_added_command", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_added_inactive", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_added_insert", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_added_normal", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_added_replace", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_added_terminal", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_added_visual", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_diff_modified_command", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_modified_inactive", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_modified_insert", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_modified_normal", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_modified_replace", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_modified_terminal", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_modified_visual", { bg = "#303030", fg = "#5dbaec" })
hi(0, "lualine_b_diff_removed_command", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diff_removed_inactive", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diff_removed_insert", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diff_removed_normal", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diff_removed_replace", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diff_removed_terminal", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_diff_removed_visual", { bg = "#303030", fg = "#ee6d29" })
hi(0, "lualine_b_inactive", { bg = "#303030", fg = "#9e9e9e" })
hi(0, "lualine_b_insert", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_normal", { bg = "#303030", fg = "#60abf1" })
hi(0, "lualine_b_replace", { bg = "#303030", fg = "#f6605b" })
hi(0, "lualine_b_terminal", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_b_visual", { bg = "#303030", fg = "#c67ddc" })
hi(0, "lualine_c_inactive", { bg = "#303030", fg = "#9e9e9e" })
hi(0, "lualine_c_normal", { bg = "#303030", fg = "#c6c6c6" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#303030", fg = "#dcca98" })
hi(0, "lualine_transitional_lualine_a_insert_to_lualine_b_insert", { bg = "#303030", fg = "#7bbd7a" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#303030", fg = "#60abf1" })
hi(0, "manHeader", { link = "MoonflyEmerald" })
hi(0, "manOptionDesc", { link = "MoonflyOrchid" })
hi(0, "manReference", { link = "MoonflyGreen" })
hi(0, "manSectionHeading", { link = "MoonflyBlue" })
hi(0, "manSubHeading", { link = "MoonflyTurquoise" })
hi(0, "markdownBold", { link = "MoonflyYellow" })
hi(0, "markdownCode", { link = "MoonflyKhaki" })
hi(0, "markdownCodeDelimiter", { link = "MoonflyKhaki" })
hi(0, "markdownError", { link = "NormalNC" })
hi(0, "markdownH1", { link = "MoonflyEmerald" })
hi(0, "markdownH2", { link = "MoonflyBlue" })
hi(0, "markdownH3", { link = "MoonflyTurquoise" })
hi(0, "markdownHeadingRule", { link = "MoonflyCranberry" })
hi(0, "markdownItalic", { fg = "#d99d93", italic = true })
hi(0, "markdownUrl", { link = "MoonflyPurple" })
hi(0, "mkdDelimiter", { link = "MoonflyWhite" })
hi(0, "mkdLineBreak", { link = "NormalNC" })
hi(0, "mkdListItem", { link = "MoonflyBlue" })
hi(0, "mkdURL", { link = "MoonflyPurple" })
hi(0, "netrwClassify", { link = "MoonflyCranberry" })
hi(0, "netrwDir", { link = "MoonflySky" })
hi(0, "netrwExe", { link = "MoonflyKhaki" })
hi(0, "qfFileName", { link = "MoonflyEmerald" })
hi(0, "shAlias", { link = "MoonflyTurquoise" })
hi(0, "shCommandSub", { link = "MoonflyWhite" })
hi(0, "shCtrlSeq", { link = "MoonflyKhaki" })
hi(0, "shLoop", { link = "MoonflyViolet" })
hi(0, "shRange", { link = "MoonflyWhite" })
hi(0, "shSetList", { link = "MoonflyTurquoise" })
hi(0, "shShellVariables", { link = "MoonflyTurquoise" })
hi(0, "shVariable", { link = "MoonflyTurquoise" })
hi(0, "snipLeadingSpaces", { bg = "#080808", fg = "#c6c6c6" })
hi(0, "tagName", { link = "MoonflyTurquoise" })
hi(0, "texBeginEndName", { link = "MoonflyEmerald" })
hi(0, "texCite", { link = "MoonflyGreen" })
hi(0, "texDocType", { link = "MoonflyCranberry" })
hi(0, "texDocTypeArgs", { link = "MoonflyOrchid" })
hi(0, "texInputFile", { link = "String" })
hi(0, "texMathZoneC", { link = "MoonflySky" })
hi(0, "texMathZoneX", { link = "MoonflySky" })
hi(0, "texRefZone", { link = "MoonflyGreen" })
hi(0, "texSection", { link = "MoonflyLavender" })
hi(0, "texTypeStyle", { link = "MoonflyYellow" })
hi(0, "texZone", { link = "MoonflyLavender" })
hi(0, "xmlAttrib", { link = "MoonflyLime" })
hi(0, "xmlEndTag", { link = "MoonflyBlue" })
hi(0, "xmlTag", { link = "MoonflyLime" })
hi(0, "xmlTagName", { link = "MoonflyBlue" })
hi(0, "yamlBlockMappingKey", { link = "MoonflySky" })
hi(0, "yamlFlowMappingKey", { link = "MoonflySky" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#323437"
g.terminal_color_1 = "#ff5454"
g.terminal_color_2 = "#8cc85f"
g.terminal_color_3 = "#e3c78a"
g.terminal_color_4 = "#80a0ff"
g.terminal_color_5 = "#cf87e8"
g.terminal_color_6 = "#79dac8"
g.terminal_color_7 = "#c6c6c6"
g.terminal_color_8 = "#949494"
g.terminal_color_9 = "#ff5189"
g.terminal_color_10 = "#36c692"
g.terminal_color_11 = "#c6c684"
g.terminal_color_12 = "#74b2ff"
g.terminal_color_13 = "#ae81ff"
g.terminal_color_14 = "#85dc85"
g.terminal_color_15 = "#e4e4e4"
