-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "hybrid"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { fg = "#d54e53", reverse = true })
hi(0, "@comment.note", { fg = "#7aa6da", reverse = true })
hi(0, "@comment.todo", { fg = "#70c0b1", reverse = true })
hi(0, "@comment.warning", { fg = "#e7c547", reverse = true })
hi(0, "@conceal", { fg = "#707880" })
hi(0, "@constructor", { fg = "#b294bb" })
hi(0, "@function.builtin", { fg = "#cc6666" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.label", { link = "@label" })
hi(0, "@lsp.type.macro", { link = "@function.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@markup.heading", { bold = true, fg = "#7aa6da" })
hi(0, "@markup.heading.1", { bold = true, fg = "#e7c547" })
hi(0, "@markup.heading.2", { bold = true, fg = "#b9ca4a" })
hi(0, "@markup.heading.3", { bold = true, fg = "#70c0b1" })
hi(0, "@markup.heading.4", { fg = "#f0c674" })
hi(0, "@markup.heading.5", { fg = "#b5bd68" })
hi(0, "@markup.heading.6", { fg = "#8abeb7" })
hi(0, "@markup.link", { fg = "#b294bb" })
hi(0, "@markup.link.label", { fg = "#7aa6da" })
hi(0, "@markup.link.url", { fg = "#8abeb7", underline = true })
hi(0, "@markup.list", { fg = "#81a2be" })
hi(0, "@markup.list.checked", { fg = "#b5bd68" })
hi(0, "@markup.list.unchecked", { fg = "#81a2be" })
hi(0, "@markup.math", { fg = "#b294bb" })
hi(0, "@markup.quote", { fg = "#81a2be" })
hi(0, "@markup.raw", { link = "Comment" })
hi(0, "@module.builtin", { fg = "#cc6666" })
hi(0, "@property", { fg = "#8abeb7" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { fg = "#b294bb" })
hi(0, "@string.regexp", { fg = "#8abeb7" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { underline = true })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@variable", { fg = "#c5c8c6" })
hi(0, "@variable.builtin", { fg = "#cc6666" })
hi(0, "@variable.member", { fg = "#8abeb7" })
hi(0, "@variable.parameter", { fg = "#f0c674" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { fg = "#8c9440" })
hi(0, "BufferLineIndicatorSelected", { fg = "#7aa6da" })
hi(0, "BufferLineOffsetSeparator", { link = "WinSeparator" })
hi(0, "Changed", { fg = "#5f819d" })
hi(0, "Character", { fg = "#b5bd68" })
hi(0, "CmpItemAbbr", { fg = "#c5c8c6" })
hi(0, "CmpItemAbbrDefault", { fg = "#c5c8c6" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#707880", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#707880" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#81a2be" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c5c8c6" })
hi(0, "CmpItemAbbrMatchFuzzy", { sp = "#81a2be", undercurl = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c5c8c6" })
hi(0, "CmpItemKindArray", { link = "@punctuation.bracket" })
hi(0, "CmpItemKindBoolean", { link = "@boolean" })
hi(0, "CmpItemKindClass", { link = "@type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "@constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#7aa6da" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "@constant" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Special" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@variable.member" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "@variable" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "@function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKey", { link = "@variable.member" })
hi(0, "CmpItemKindKeyword", { link = "@keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "@function.method" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@module" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindNamespace", { link = "@module" })
hi(0, "CmpItemKindNull", { link = "@constant.builtin" })
hi(0, "CmpItemKindNumber", { link = "@number" })
hi(0, "CmpItemKindObject", { link = "@constant" })
hi(0, "CmpItemKindOperator", { link = "@operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPackage", { link = "@module" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "@markup.link" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Conceal" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindString", { link = "@string" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "@comment" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Typedef" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Structure" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "@string" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "@variable" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#707880" })
hi(0, "CmpItemMenuDefault", { fg = "#c5c8c6" })
hi(0, "ColorColumn", { bg = "#08090a" })
hi(0, "Comment", { fg = "#707880", italic = true })
hi(0, "Conceal", { fg = "#5f819d" })
hi(0, "Constant", { fg = "#de935f" })
hi(0, "CurSearch", { bg = "#111314", fg = "#b5bd68", reverse = true })
hi(0, "Cursor", { reverse = true })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#1b1e22" })
hi(0, "CursorLineNr", { bg = "#1b1e22", fg = "#7aa6da" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#b5bd68" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#707880" })
hi(0, "DapUIBreakpointsInfo", { fg = "#b5bd68" })
hi(0, "DapUIBreakpointsLine", { link = "DapUILineNumber" })
hi(0, "DapUIBreakpointsPath", { fg = "#8abeb7" })
hi(0, "DapUICurrentFrameName", { link = "DapUIBreakpointsCurrentLine" })
hi(0, "DapUIDecoration", { fg = "#8abeb7" })
hi(0, "DapUIEndofBuffer", { link = "EndOfBuffer" })
hi(0, "DapUIFloatBorder", { fg = "#8abeb7" })
hi(0, "DapUIFloatNormal", { link = "NormalFloat" })
hi(0, "DapUIFrameName", { link = "Normal" })
hi(0, "DapUILineNumber", { fg = "#8abeb7" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#8abeb7" })
hi(0, "DapUINormal", { link = "Normal" })
hi(0, "DapUIPlayPause", { fg = "#b5bd68" })
hi(0, "DapUIRestart", { fg = "#b5bd68" })
hi(0, "DapUIScope", { fg = "#8abeb7" })
hi(0, "DapUISource", { fg = "#b294bb" })
hi(0, "DapUIStepBack", { fg = "#8abeb7" })
hi(0, "DapUIStepInto", { fg = "#8abeb7" })
hi(0, "DapUIStepOut", { fg = "#8abeb7" })
hi(0, "DapUIStepOver", { fg = "#8abeb7" })
hi(0, "DapUIStop", { fg = "#cc6666" })
hi(0, "DapUIStoppedThread", { fg = "#8abeb7" })
hi(0, "DapUIThread", { fg = "#b5bd68" })
hi(0, "DapUIType", { fg = "#b294bb" })
hi(0, "DapUIUnavailable", { fg = "#707880" })
hi(0, "DapUIValue", { link = "Normal" })
hi(0, "DapUIVariable", { link = "Normal" })
hi(0, "DapUIWatchesEmpty", { fg = "#cc6666" })
hi(0, "DapUIWatchesError", { fg = "#cc6666" })
hi(0, "DapUIWatchesValue", { fg = "#b5bd68" })
hi(0, "DapUIWinSelect", { bold = true, fg = "#8abeb7" })
hi(0, "DashboardFooter", { fg = "#7aa6da" })
hi(0, "DashboardHeader", { fg = "#7aa6da" })
hi(0, "Debug", { fg = "#de935f" })
hi(0, "Delimiter", { fg = "#c5c8c6" })
hi(0, "DiagnosticError", { fg = "#d54e53" })
hi(0, "DiagnosticHint", { fg = "#70c0b1" })
hi(0, "DiagnosticInfo", { fg = "#7aa6da" })
hi(0, "DiagnosticOk", { fg = "#b9ca4a" })
hi(0, "DiagnosticUnderlineError", { sp = "#d54e53", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#70c0b1", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#7aa6da", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#b9ca4a", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e7c547", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#23181a", fg = "#d54e53" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#192323", fg = "#70c0b1" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#1a2128", fg = "#7aa6da" })
hi(0, "DiagnosticVirtualTextOk", { bg = "#21241a", fg = "#70c0b1" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#25241a", fg = "#e7c547" })
hi(0, "DiagnosticWarn", { fg = "#e7c547" })
hi(0, "DiffAdd", { bg = "#272a1c" })
hi(0, "DiffChange", { bg = "#1f272e" })
hi(0, "DiffDelete", { bg = "#2b1a1c" })
hi(0, "DiffText", { bg = "#3a434a" })
hi(0, "Directory", { fg = "#81a2be" })
hi(0, "EndOfBuffer", { fg = "#707880" })
hi(0, "Error", { fg = "#d54e53", reverse = true })
hi(0, "ErrorMsg", { fg = "#d54e53" })
hi(0, "FloatBorder", { bg = "#08090a", fg = "#5f819d" })
hi(0, "FloatShadow", { bg = "#43464c", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#43464c", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#08090a", fg = "#81a2be" })
hi(0, "FoldColumn", { bg = "#111314", fg = "#707880" })
hi(0, "Folded", { bg = "#1b1e22", fg = "#c5c8c6", italic = true })
hi(0, "Function", { fg = "#81a2be" })
hi(0, "GitSignsAdd", { fg = "#8c9440" })
hi(0, "GitSignsChange", { fg = "#5f819d" })
hi(0, "GitSignsDelete", { fg = "#a54242" })
hi(0, "GitSignsStagedAdd", { fg = "#464a20" })
hi(0, "GitSignsStagedAddCul", { fg = "#464a20" })
hi(0, "GitSignsStagedAddLn", { bg = "#272a1c" })
hi(0, "GitSignsStagedAddNr", { fg = "#464a20" })
hi(0, "GitSignsStagedChange", { fg = "#2f404e" })
hi(0, "GitSignsStagedChangeCul", { fg = "#2f404e" })
hi(0, "GitSignsStagedChangeLn", { bg = "#1f272e" })
hi(0, "GitSignsStagedChangeNr", { fg = "#2f404e" })
hi(0, "GitSignsStagedChangedelete", { fg = "#2f404e" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#2f404e" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#1f272e" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#2f404e" })
hi(0, "GitSignsStagedDelete", { fg = "#522121" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#522121" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#522121" })
hi(0, "GitSignsStagedTopdelete", { fg = "#522121" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#522121" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#522121" })
hi(0, "GitSignsStagedUntracked", { fg = "#464a20" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#464a20" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#272a1c" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#464a20" })
hi(0, "Identifier", { fg = "#c5c8c6" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "IncSearch", { bg = "#111314", fg = "#de935f", reverse = true })
hi(0, "LineNr", { fg = "#373b41" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspReferenceRead", { bg = "#2b2f35", bold = true })
hi(0, "LspReferenceText", { bg = "#2b2f35" })
hi(0, "LspReferenceWrite", { bg = "#2b2f35", bold = true, underline = true })
hi(0, "MatchParen", { bg = "#2b2f35", bold = true })
hi(0, "ModeMsg", { fg = "#7aa6da" })
hi(0, "MoreMsg", { fg = "#7aa6da" })
hi(0, "NavicIconsArray", { link = "@punctuation.bracket" })
hi(0, "NavicIconsBoolean", { link = "@boolean" })
hi(0, "NavicIconsClass", { link = "@type" })
hi(0, "NavicIconsColor", { link = "Special" })
hi(0, "NavicIconsConstant", { link = "@constant" })
hi(0, "NavicIconsConstructor", { link = "@constructor" })
hi(0, "NavicIconsEnum", { link = "Structure" })
hi(0, "NavicIconsEnumMember", { link = "@constant" })
hi(0, "NavicIconsEvent", { link = "Special" })
hi(0, "NavicIconsField", { link = "@variable.member" })
hi(0, "NavicIconsFile", { link = "@variable" })
hi(0, "NavicIconsFolder", { link = "Directory" })
hi(0, "NavicIconsFunction", { link = "@function" })
hi(0, "NavicIconsInterface", { link = "Structure" })
hi(0, "NavicIconsKey", { link = "@variable.member" })
hi(0, "NavicIconsKeyword", { link = "@keyword" })
hi(0, "NavicIconsMethod", { link = "@function.method" })
hi(0, "NavicIconsModule", { link = "@module" })
hi(0, "NavicIconsNamespace", { link = "@module" })
hi(0, "NavicIconsNull", { link = "@constant.builtin" })
hi(0, "NavicIconsNumber", { link = "@number" })
hi(0, "NavicIconsObject", { link = "@constant" })
hi(0, "NavicIconsOperator", { link = "@operator" })
hi(0, "NavicIconsPackage", { link = "@module" })
hi(0, "NavicIconsProperty", { link = "@property" })
hi(0, "NavicIconsReference", { link = "@markup.link" })
hi(0, "NavicIconsSnippet", { link = "Conceal" })
hi(0, "NavicIconsString", { link = "@string" })
hi(0, "NavicIconsStruct", { link = "Structure" })
hi(0, "NavicIconsText", { link = "@comment" })
hi(0, "NavicIconsTypeParameter", { link = "Typedef" })
hi(0, "NavicIconsUnit", { link = "Structure" })
hi(0, "NavicIconsValue", { link = "@string" })
hi(0, "NavicIconsVariable", { link = "@variable" })
hi(0, "NavicSeparator", { fg = "#c5c8c6" })
hi(0, "NavicText", { fg = "#c5c8c6" })
hi(0, "NeoTreeDimText", { fg = "#707880" })
hi(0, "NeoTreeFileIcon", { fg = "#c5c8c6" })
hi(0, "NeoTreeFloatTitle", { fg = "#81a2be" })
hi(0, "NeoTreeGitAdded", { fg = "#8c9440" })
hi(0, "NeoTreeGitConflict", { fg = "#de935f" })
hi(0, "NeoTreeGitDeleted", { fg = "#a54242" })
hi(0, "NeoTreeGitIgnored", { fg = "#707880" })
hi(0, "NeoTreeGitModified", { fg = "#5f819d" })
hi(0, "NeoTreeGitStaged", { fg = "#8c9440" })
hi(0, "NeoTreeGitUnstaged", { fg = "#5f819d" })
hi(0, "NeoTreeGitUntracked", { fg = "#8c9440" })
hi(0, "NeoTreeRootName", { fg = "#7aa6da" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#8abeb7" })
hi(0, "NonText", { fg = "#373b41" })
hi(0, "Normal", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "NormalFloat", { bg = "#08090a", fg = "#c5c8c6" })
hi(0, "NormalNC", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "NvimInternalError", { bg = "#e80000", ctermbg = 9, ctermfg = 9, fg = "#ff0000" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#b5bd68" })
hi(0, "NvimTreeGitDeletedIcon", { fg = "#a54242" })
hi(0, "NvimTreeGitDirtyIcon", { fg = "#5f819d" })
hi(0, "NvimTreeGitIgnoredIcon", { fg = "#707880" })
hi(0, "NvimTreeGitMergeIcon", { fg = "#de935f" })
hi(0, "NvimTreeGitNewIcon", { fg = "#8c9440" })
hi(0, "NvimTreeGitRenamedIcon", { fg = "#5f819d" })
hi(0, "NvimTreeGitStagedIcon", { fg = "#8c9440" })
hi(0, "NvimTreeImageFile", { fg = "#b294bb" })
hi(0, "NvimTreeIndentMarker", { fg = "#707880" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#81a2be" })
hi(0, "NvimTreeSpecialFile", { fg = "#f0c674", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#8abeb7" })
hi(0, "NvimTreeWindowPicker", { bg = "#1b1e22", bold = true, fg = "#7aa6da" })
hi(0, "Operator", { fg = "#81a2be" })
hi(0, "Pmenu", { bg = "#08090a", fg = "#c5c8c6" })
hi(0, "PmenuSbar", { bg = "#08090a" })
hi(0, "PmenuSel", { bg = "#2b2f35", bold = true })
hi(0, "PmenuThumb", { bg = "#2b2f35" })
hi(0, "PreProc", { fg = "#b294bb" })
hi(0, "Question", { fg = "#7aa6da" })
hi(0, "QuickFixLine", { bg = "#2b2f35", bold = true })
hi(0, "RedrawDebugClear", { bg = "#5c4700", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#00471b", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#440005", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { fg = "#a54242" })
hi(0, "Search", { bg = "#111314", fg = "#f0c674", reverse = true })
hi(0, "SignColumn", { bg = "#111314", fg = "#707880" })
hi(0, "Special", { fg = "#7aa6da" })
hi(0, "SpecialKey", { fg = "#7aa6da" })
hi(0, "SpellBad", { sp = "#d54e53", undercurl = true })
hi(0, "SpellCap", { sp = "#e7c547", undercurl = true })
hi(0, "SpellLocal", { sp = "#7aa6da", undercurl = true })
hi(0, "SpellRare", { sp = "#70c0b1", undercurl = true })
hi(0, "Statement", { fg = "#b294bb" })
hi(0, "StatusLine", { bg = "#1b1e22", fg = "#c5c8c6" })
hi(0, "StatusLineNC", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "String", { fg = "#b5bd68" })
hi(0, "TabLine", { bg = "#08090a", fg = "#c5c8c6" })
hi(0, "TabLineFill", { bg = "#08090a", fg = "#c5c8c6" })
hi(0, "TabLineSel", { bg = "#111314", bold = true, fg = "#c5c8c6" })
hi(0, "TelescopeBorder", { bg = "#08090a", fg = "#5f819d" })
hi(0, "TelescopeMatching", { bold = true, fg = "#81a2be" })
hi(0, "TelescopeNormal", { bg = "#08090a", fg = "#c5c8c6" })
hi(0, "TelescopeTitle", { bg = "#08090a", fg = "#81a2be" })
hi(0, "Title", { bold = true, fg = "#7aa6da" })
hi(0, "Todo", { fg = "#70c0b1", reverse = true })
hi(0, "Type", { fg = "#70c0b1" })
hi(0, "Visual", { bg = "#37333e" })
-- hi(0, "Visual", { bg = "#384454" })
hi(0, "WarningMsg", { fg = "#e7c547" })
hi(0, "WhichKey", { fg = "#7aa6da" })
hi(0, "WhichKeyDesc", { fg = "#c5c8c6" })
hi(0, "WhichKeyGroup", { fg = "#b5bd68" })
hi(0, "WildMenu", { bg = "#2b2f35", bold = true, fg = "#c5c8c6" })
hi(0, "WinBar", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "WinBarNC", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "WinSeparator", { bg = "#111314", fg = "#707880" })
hi(0, "debugBreakpoint", { bg = "#1b2025", fg = "#81a2be" })
hi(0, "debugPC", { bg = "#26241e" })
hi(0, "diffAdded", { fg = "#8c9440" })
hi(0, "diffChanged", { fg = "#5f819d" })
hi(0, "diffFile", { fg = "#81a2be" })
hi(0, "diffIndexLine", { fg = "#b294bb" })
hi(0, "diffLine", { fg = "#707880" })
hi(0, "diffNewFile", { fg = "#de935f" })
hi(0, "diffOldFile", { fg = "#f0c674" })
hi(0, "diffRemoved", { fg = "#a54242" })
hi(0, "healthError", { link = "DiagnosticError" })
hi(0, "healthSuccess", { link = "DiagnosticOk" })
hi(0, "healthWarning", { link = "DiagnosticWarn" })
hi(0, "lCursor", { bg = "#b7bab8", fg = "#1d1f21" })
hi(0, "lualine_a_command", { bg = "#e2b866", fg = "#1d1f21" })
hi(0, "lualine_a_inactive", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "lualine_a_insert", { bg = "#a8af5a", fg = "#1d1f21" })
hi(0, "lualine_a_normal", { bg = "#7495b0", fg = "#1d1f21" })
hi(0, "lualine_a_replace", { bg = "#bd595a", fg = "#1d1f21" })
hi(0, "lualine_a_terminal", { bg = "#7db0a9", fg = "#1d1f21" })
hi(0, "lualine_a_visual", { bg = "#a487ad", fg = "#1d1f21" })
hi(0, "lualine_b_command", { bg = "#433d30", fg = "#c5c8c6" })
hi(0, "lualine_b_diagnostics_error_command", { bg = "#433d30", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_error_inactive", { bg = "#111314", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_error_insert", { bg = "#373b2e", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_error_normal", { bg = "#2d363f", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_error_replace", { bg = "#3c2a2d", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_error_terminal", { bg = "#2f3c3d", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_error_visual", { bg = "#37333e", fg = "#d54e53" })
hi(0, "lualine_b_diagnostics_hint_command", { bg = "#433d30", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_hint_inactive", { bg = "#111314", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_hint_insert", { bg = "#373b2e", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_hint_normal", { bg = "#2d363f", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_hint_replace", { bg = "#3c2a2d", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_hint_terminal", { bg = "#2f3c3d", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_hint_visual", { bg = "#37333e", fg = "#70c0b1" })
hi(0, "lualine_b_diagnostics_info_command", { bg = "#433d30", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_info_inactive", { bg = "#111314", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_info_insert", { bg = "#373b2e", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_info_normal", { bg = "#2d363f", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_info_replace", { bg = "#3c2a2d", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_info_terminal", { bg = "#2f3c3d", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_info_visual", { bg = "#37333e", fg = "#7aa6da" })
hi(0, "lualine_b_diagnostics_warn_command", { bg = "#433d30", fg = "#e7c547" })
hi(0, "lualine_b_diagnostics_warn_inactive", { bg = "#111314", fg = "#e7c547" })
hi(0, "lualine_b_diagnostics_warn_insert", { bg = "#373b2e", fg = "#e7c547" })
hi(0, "lualine_b_diagnostics_warn_normal", { bg = "#2d363f", fg = "#e7c547" })
hi(0, "lualine_b_diagnostics_warn_replace", { bg = "#3c2a2d", fg = "#e7c547" })
hi(0, "lualine_b_diagnostics_warn_terminal", { bg = "#2f3c3d", fg = "#e7c547" })
hi(0, "lualine_b_diagnostics_warn_visual", { bg = "#37333e", fg = "#e7c547" })
hi(0, "lualine_b_diff_added_command", { bg = "#433d30", fg = "#8c9440" })
hi(0, "lualine_b_diff_added_inactive", { bg = "#111314", fg = "#8c9440" })
hi(0, "lualine_b_diff_added_insert", { bg = "#373b2e", fg = "#8c9440" })
hi(0, "lualine_b_diff_added_normal", { bg = "#2d363f", fg = "#8c9440" })
hi(0, "lualine_b_diff_added_replace", { bg = "#3c2a2d", fg = "#8c9440" })
hi(0, "lualine_b_diff_added_terminal", { bg = "#2f3c3d", fg = "#8c9440" })
hi(0, "lualine_b_diff_added_visual", { bg = "#37333e", fg = "#8c9440" })
hi(0, "lualine_b_diff_modified_command", { bg = "#433d30", fg = "#5f819d" })
hi(0, "lualine_b_diff_modified_inactive", { bg = "#111314", fg = "#5f819d" })
hi(0, "lualine_b_diff_modified_insert", { bg = "#373b2e", fg = "#5f819d" })
hi(0, "lualine_b_diff_modified_normal", { bg = "#2d363f", fg = "#5f819d" })
hi(0, "lualine_b_diff_modified_replace", { bg = "#3c2a2d", fg = "#5f819d" })
hi(0, "lualine_b_diff_modified_terminal", { bg = "#2f3c3d", fg = "#5f819d" })
hi(0, "lualine_b_diff_modified_visual", { bg = "#37333e", fg = "#5f819d" })
hi(0, "lualine_b_diff_removed_command", { bg = "#433d30", fg = "#a54242" })
hi(0, "lualine_b_diff_removed_inactive", { bg = "#111314", fg = "#a54242" })
hi(0, "lualine_b_diff_removed_insert", { bg = "#373b2e", fg = "#a54242" })
hi(0, "lualine_b_diff_removed_normal", { bg = "#2d363f", fg = "#a54242" })
hi(0, "lualine_b_diff_removed_replace", { bg = "#3c2a2d", fg = "#a54242" })
hi(0, "lualine_b_diff_removed_terminal", { bg = "#2f3c3d", fg = "#a54242" })
hi(0, "lualine_b_diff_removed_visual", { bg = "#37333e", fg = "#a54242" })
hi(0, "lualine_b_inactive", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "lualine_b_insert", { bg = "#373b2e", fg = "#c5c8c6" })
hi(0, "lualine_b_normal", { bg = "#2d363f", fg = "#c5c8c6" })
hi(0, "lualine_b_replace", { bg = "#3c2a2d", fg = "#c5c8c6" })
hi(0, "lualine_b_terminal", { bg = "#2f3c3d", fg = "#c5c8c6" })
hi(0, "lualine_b_visual", { bg = "#37333e", fg = "#c5c8c6" })
hi(0, "lualine_c_inactive", { bg = "#111314", fg = "#c5c8c6" })
hi(0, "lualine_c_normal", { bg = "#1b1e22", fg = "#c5c8c6" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#433d30", fg = "#f0c674" })
hi(
	0,
	"lualine_transitional_lualine_a_command_to_lualine_b_diagnostics_warn_command",
	{ bg = "#433d30", fg = "#f0c674" }
)
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_diagnostics_warn_normal", { bg = "#2d363f", fg = "#81a2be" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#2d363f", fg = "#81a2be" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_normal", { bg = "#1b1e22", fg = "#4f493c" })
hi(0, "lualine_transitional_lualine_b_diagnostics_warn_command_to_lualine_c_normal", { bg = "#1b1e22", fg = "#4f493c" })
hi(0, "lualine_transitional_lualine_b_diagnostics_warn_normal_to_lualine_c_normal", { bg = "#1b1e22", fg = "#39424b" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#1b1e22", fg = "#39424b" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1d1f21"
g.terminal_color_1 = "#cc6666"
g.terminal_color_2 = "#b5bd68"
g.terminal_color_3 = "#f0c674"
g.terminal_color_4 = "#81a2be"
g.terminal_color_5 = "#b294bb"
g.terminal_color_6 = "#8abeb7"
g.terminal_color_7 = "#c5c8c6"
g.terminal_color_8 = "#373b41"
g.terminal_color_9 = "#d54e53"
g.terminal_color_10 = "#b9ca4a"
g.terminal_color_11 = "#e7c547"
g.terminal_color_12 = "#7aa6da"
g.terminal_color_13 = "#c397d8"
g.terminal_color_14 = "#70c0b1"
g.terminal_color_15 = "#eaeaea"
