-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "jellybeans"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#f999b9" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag.delimiter", { fg = "#506680" })
hi(0, "@text.emphasis", { link = "Italic" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { fg = "#8abee5" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { link = "Normal" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#a2fac1" })
hi(0, "Bold", { bold = true })
hi(0, "Changed", { ctermfg = 14, fg = "#7cfaff" })
hi(0, "CmpItemAbbrDefault", { fg = "#ffffff" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#878787" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#ffffff" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#ffffff" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#7bc4ad" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenuDefault", { fg = "#ffffff" })
hi(0, "ColorColumn", { bg = "#000000" })
hi(0, "Comment", { fg = "#878787" })
hi(0, "Conceal", { fg = "#8abee5" })
hi(0, "Constant", { fg = "#d76331" })
hi(0, "CurSearch", { bg = "#fce094", ctermbg = 11, ctermfg = 0, fg = "#070810" })
hi(0, "Cursor", { bg = "#b2d1f0", fg = "#141414" })
hi(0, "CursorColumn", { bg = "#1c1c1c" })
hi(0, "CursorLine", { bg = "#1c1c1c" })
hi(0, "CursorLineNr", { fg = "#d3c1be" })
hi(0, "Delimiter", { fg = "#5f87a1" })
hi(0, "DiagnosticError", { ctermfg = 9, fg = "#ffbeb2" })
hi(0, "DiagnosticHint", { ctermfg = 12, fg = "#a7daff" })
hi(0, "DiagnosticInfo", { ctermfg = 14, fg = "#7cfaff" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#a2fac1" })
hi(0, "DiagnosticWarn", { ctermfg = 11, fg = "#f9e28a" })
hi(0, "DiffAdd", { bg = "#437119", fg = "#c5efb4" })
hi(0, "DiffChange", { bg = "#2b5c78" })
hi(0, "DiffDelete", { bg = "#70008a", fg = "#420105" })
hi(0, "DiffText", { bg = "#000000", fg = "#8abee5" })
hi(0, "Directory", { fg = "#d7d278" })
hi(0, "Error", { bg = "#922020" })
hi(0, "ErrorMsg", { bg = "#922020" })
hi(0, "FoldColumn", { bg = "#1f1f1f", fg = "#4e5c6c" })
hi(0, "Folded", { bg = "#374048", fg = "#9aa8b9" })
hi(0, "Function", { fg = "#f8d16b" })
hi(0, "GitSignsAdd", { fg = "#55be4d" })
hi(0, "GitSignsChange", { fg = "#fabd60" })
hi(0, "GitSignsDelete", { fg = "#d01c00" })
hi(0, "GitSignsStagedAdd", { fg = "#2c5e27" })
hi(0, "GitSignsStagedAddCul", { fg = "#2c5e27" })
hi(0, "GitSignsStagedAddLn", { bg = "#437119", fg = "#627858" })
hi(0, "GitSignsStagedAddNr", { fg = "#2c5e27" })
hi(0, "GitSignsStagedChange", { fg = "#805e27" })
hi(0, "GitSignsStagedChangeCul", { fg = "#805e27" })
hi(0, "GitSignsStagedChangeLn", { bg = "#2b5c78" })
hi(0, "GitSignsStagedChangeNr", { fg = "#805e27" })
hi(0, "GitSignsStagedChangedelete", { fg = "#805e27" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#805e27" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#2b5c78" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#805e27" })
hi(0, "GitSignsStagedDelete", { fg = "#690e04" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#690e04" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#690e04" })
hi(0, "GitSignsStagedTopdelete", { fg = "#690e04" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#690e04" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#690e04" })
hi(0, "GitSignsStagedUntracked", { fg = "#2c5e27" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#2c5e27" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#437119", fg = "#627858" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#2c5e27" })
hi(0, "Identifier", { fg = "#cbb1f2" })
hi(0, "Include", { fg = "#8195cb", italic = true })
hi(0, "Italic", { italic = true })
hi(0, "LazyBold", { bold = true })
hi(0, "LazyItalic", { italic = true })
hi(0, "LineNr", { fg = "#695551" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#d01c00" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#c5efb4" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#b1d0f6" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#fabd60" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#c92c2c", undercurl = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#d1ebbd", undercurl = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#b2d1f0", undercurl = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#ffba66", undercurl = true })
hi(0, "LspDiagnosticsVirtualTextError", { bg = "#2a0909", fg = "#d01c00" })
hi(0, "LspDiagnosticsVirtualTextHint", { bg = "#131f0a", fg = "#c5efb4" })
hi(0, "LspDiagnosticsVirtualTextInformation", { bg = "#091c2f", fg = "#b1d0f6" })
hi(0, "LspDiagnosticsVirtualTextWarning", { bg = "#291600", fg = "#fabd60" })
hi(0, "LspReferenceRead", { bg = "#262626" })
hi(0, "LspReferenceText", { bg = "#262626" })
hi(0, "LspReferenceWrite", { bg = "#262626" })
hi(0, "MatchParen", { bold = true, fg = "#f999b9" })
hi(0, "ModeMsg", { ctermfg = 10, fg = "#a2fac1" })
hi(0, "MoreMsg", { fg = "#6da266" })
hi(0, "NoiceAttr288", { fg = "#79a4e4" })
hi(0, "NoiceAttr471", { bg = "#922020" })
hi(0, "NoiceAttr9", { fg = "#a2fac1" })
hi(0, "NoiceFormatProgressDone", { bg = "#312129", fg = "#f999b9" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#616161" })
hi(0, "Normal", { bg = "#141414", fg = "#e6eac7" })
hi(0, "NvimInternalError", { bg = "#ff0000", ctermbg = 9, ctermfg = 9, fg = "#f23a00" })
hi(0, "NvimTreeGitDeleted", { link = "GitSignsDelete" })
hi(0, "NvimTreeGitDirty", { link = "GitSignsChange" })
hi(0, "NvimTreeGitMerge", { link = "GitSignsChange" })
hi(0, "NvimTreeGitNew", { link = "GitSignsAdd" })
hi(0, "NvimTreeGitRenamed", { link = "GitSignsChange" })
hi(0, "NvimTreeGitStaged", { fg = "#c5efb4" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d7d278" })
hi(0, "Operator", { fg = "#8abee5" })
hi(0, "Pmenu", { bg = "#1f1f1f", fg = "#ffffff" })
hi(0, "PmenuSel", { bg = "#8297c0", bold = true, fg = "#000000" })
hi(0, "PreProc", { fg = "#8195cb" })
hi(0, "Question", { fg = "#55be4d" })
hi(0, "QuickFixLine", { bg = "#374048" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffbeb2" })
hi(0, "Search", { bg = "#312129", fg = "#f999b9" })
hi(0, "SignColumn", { fg = "#787878" })
hi(0, "Sneak", { link = "Search" })
hi(0, "Special", { fg = "#7bc4ad" })
hi(0, "SpecialKey", { bg = "#1c1c1c", fg = "#404040" })
hi(0, "SpellBad", { bg = "#922020" })
hi(0, "SpellCap", { bg = "#0000e0" })
hi(0, "SpellLocal", { bg = "#2d7168" })
hi(0, "SpellRare", { bg = "#520061" })
hi(0, "Statement", { fg = "#b1d0f6" })
hi(0, "StatusLine", { bg = "#1c1c1c", fg = "#ffffff" })
hi(0, "StatusLineNC", { bg = "#1c1c1c", fg = "#c7c7c7" })
hi(0, "String", { fg = "#91b263" })
hi(0, "StringDelimiter", { fg = "#4f682f" })
hi(0, "Structure", { fg = "#8abee5" })
hi(0, "TabLine", { bg = "#000000", fg = "#abb9c7" })
hi(0, "TabLineFill", { fg = "#8b99ac" })
hi(0, "TabLineSel", { bg = "#000000", fg = "#55be4d" })
hi(0, "TelescopeBorder", { fg = "#8195cb" })
hi(0, "TelescopeMatching", { link = "Search" })
hi(0, "TelescopePromptPrefix", { fg = "#fabd60" })
hi(0, "TelescopeSelection", { bg = "#1b2536", fg = "#bac6e3" })
hi(0, "TelescopeSelectionCaret", { fg = "#fabd60" })
hi(0, "Title", { fg = "#55be4d" })
hi(0, "Todo", { fg = "#c7c7c7" })
hi(0, "Type", { fg = "#fabd60", italic = true })
hi(0, "VertSplit", { fg = "#463a47" })
hi(0, "Visual", { bg = "#404040" })
hi(0, "WarningMsg", { ctermfg = 11, fg = "#f9e28a" })
hi(0, "WildMenu", { bg = "#312129", fg = "#f999b9" })
hi(0, "WinBar", { bg = "#07080d", bold = true, fg = "#979daf" })
hi(0, "WinBarNC", { bg = "#07080d", fg = "#979daf" })
hi(0, "WinSeparator", { fg = "#463a47" })
hi(0, "lCursor", { bg = "#e8e8d4", fg = "#141414" })
hi(0, "lualine_a_command", { bg = "#d8c7ff", bold = true, fg = "#161616" })
hi(0, "lualine_a_inactive", { bg = "#8fa6d3", bold = true, fg = "#161616" })
hi(0, "lualine_a_insert", { bg = "#a9bf75", bold = true, fg = "#161616" })
hi(0, "lualine_a_normal", { bg = "#8fa6d3", bold = true, fg = "#161616" })
hi(0, "lualine_a_replace", { bg = "#e37351", bold = true, fg = "#161616" })
hi(0, "lualine_a_terminal", { bg = "#d8c7ff", bold = true, fg = "#161616" })
hi(0, "lualine_a_visual", { bg = "#98d4bb", bold = true, fg = "#161616" })
hi(0, "lualine_b_command", { bg = "#161616", fg = "#ddc5fc" })
hi(0, "lualine_b_diagnostics_error_command", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_error_inactive", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_error_insert", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_error_normal", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_error_replace", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_error_terminal", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_error_visual", { bg = "#161616", fg = "#ffbeb2" })
hi(0, "lualine_b_diagnostics_hint_command", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_hint_inactive", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_hint_insert", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_hint_normal", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_hint_replace", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_hint_terminal", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_hint_visual", { bg = "#161616", fg = "#a7daff" })
hi(0, "lualine_b_diagnostics_info_command", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_info_inactive", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_info_insert", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_info_normal", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_info_replace", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_info_terminal", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_info_visual", { bg = "#161616", fg = "#7cfaff" })
hi(0, "lualine_b_diagnostics_warn_command", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diagnostics_warn_inactive", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diagnostics_warn_insert", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diagnostics_warn_normal", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diagnostics_warn_replace", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diagnostics_warn_terminal", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diagnostics_warn_visual", { bg = "#161616", fg = "#f9e28a" })
hi(0, "lualine_b_diff_added_command", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_added_inactive", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_added_insert", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_added_normal", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_added_replace", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_added_terminal", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_added_visual", { bg = "#161616", fg = "#55be4d" })
hi(0, "lualine_b_diff_modified_command", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_modified_inactive", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_modified_insert", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_modified_normal", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_modified_replace", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_modified_terminal", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_modified_visual", { bg = "#161616", fg = "#fabd60" })
hi(0, "lualine_b_diff_removed_command", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_diff_removed_inactive", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_diff_removed_insert", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_diff_removed_normal", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_diff_removed_replace", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_diff_removed_terminal", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_diff_removed_visual", { bg = "#161616", fg = "#d01c00" })
hi(0, "lualine_b_inactive", { bg = "#161616", fg = "#8fa4dd" })
hi(0, "lualine_b_insert", { bg = "#161616", fg = "#9fc36d" })
hi(0, "lualine_b_normal", { bg = "#161616", fg = "#8fa4dd" })
hi(0, "lualine_b_replace", { bg = "#161616", fg = "#ea6e36" })
hi(0, "lualine_b_terminal", { bg = "#161616", fg = "#ddc5fc" })
hi(0, "lualine_b_visual", { bg = "#161616", fg = "#87d7be" })
hi(0, "lualine_c_command", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_c_inactive", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_c_insert", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_c_normal", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_c_replace", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_c_terminal", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_c_visual", { bg = "#1e1e1e", fg = "#feffee" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#161616", fg = "#ddc5fc" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_diagnostics_warn_command", { bg = "#161616", fg = "#ddc5fc" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_c_command", { bg = "#1e1e1e", fg = "#ddc5fc" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_diagnostics_warn_normal", { bg = "#161616", fg = "#8fa4dd" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#161616", fg = "#8fa4dd" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_c_normal", { bg = "#1e1e1e", fg = "#8fa4dd" })
hi(0, "lualine_transitional_lualine_a_visual_to_lualine_b_diagnostics_warn_visual", { bg = "#161616", fg = "#87d7be" })
hi(0, "lualine_transitional_lualine_a_visual_to_lualine_b_visual", { bg = "#161616", fg = "#87d7be" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_command", { bg = "#1e1e1e", fg = "#161616" })
hi(0, "lualine_transitional_lualine_b_diagnostics_warn_command_to_lualine_c_command", { bg = "#1e1e1e", fg = "#161616" })
hi(0, "lualine_transitional_lualine_b_diagnostics_warn_normal_to_lualine_c_normal", { bg = "#1e1e1e", fg = "#161616" })
hi(0, "lualine_transitional_lualine_b_diagnostics_warn_visual_to_lualine_c_visual", { bg = "#1e1e1e", fg = "#161616" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#1e1e1e", fg = "#161616" })
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_c_visual", { bg = "#1e1e1e", fg = "#161616" })
hi(0, "nvim_set_hl_x_hi_clear_bugfix", { fg = "#f23a00" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1d1f21"
g.terminal_color_1 = "#cc6666"
g.terminal_color_2 = "#b5bd68"
g.terminal_color_3 = "#f0c674"
g.terminal_color_4 = "#81a2be"
g.terminal_color_5 = "#b294bb"
g.terminal_color_6 = "#8abeb7"
g.terminal_color_7 = "#c5c8c6"
g.terminal_color_8 = "#373b41"
g.terminal_color_9 = "#d54e53"
g.terminal_color_10 = "#b9ca4a"
g.terminal_color_11 = "#e7c547"
g.terminal_color_12 = "#7aa6da"
g.terminal_color_13 = "#c397d8"
g.terminal_color_14 = "#70c0b1"
g.terminal_color_15 = "#eaeaea"
