-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim
-- Light saturation version of Oneminimal

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "oneminimal_light"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "@comment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.note", { link = "@text.note" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Identifier" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "@keyword" })
hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { bold = true, fg = "#8cd4ae" })
hi(0, "@keyword.directive", { bold = true, fg = "#94c6fa" })
hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
hi(0, "@keyword.exception", { link = "@keyword" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { bold = true, fg = "#94c6fa" })
hi(0, "@keyword.operator", { link = "@keyword" })
hi(0, "@keyword.repeat", { link = "@keyword" })
hi(0, "@keyword.return", { bold = true, fg = "#ebb481" })
hi(0, "@keyword.storage", { bold = true, fg = "#c1c1c1" })
hi(0, "@lsp.mod.deprecated", { fg = "#f5aaa9" })
hi(0, "@lsp.type.class", { link = "@structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "@module" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(
	0,
	"@markup.heading.1.delimiter.vimdoc",
	{ bg = "#121212", fg = "#2a2a2a", nocombine = true, sp = "#a6a6a6", underdouble = true }
)
hi(
	0,
	"@markup.heading.2.delimiter.vimdoc",
	{ bg = "#121212", fg = "#2a2a2a", nocombine = true, sp = "#a6a6a6", underline = true }
)
hi(0, "@markup.italic", { link = "@text.emphasis" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@markup.link" })
hi(0, "@markup.link.url", { fg = "#c1c1c1", underline = true })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
hi(0, "@markup.math", { link = "@string.special" })
hi(0, "@markup.quote", { link = "@string.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.strikethrough", { link = "@text.strike" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@markup.underline", { link = "@text.underline" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@module.builtin", { link = "@variable.builtin" })
hi(0, "@namespace", { link = "Identifier" })
hi(0, "@none", { link = "Normal" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@parameter", { fg = "#94c6fa" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@punctuation.bracket", { link = "@punctuation" })
hi(0, "@punctuation.delimiter", { link = "@punctuation" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.documentation", { link = "@string" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Directory" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.url", { link = "@markup.link.url" })
hi(0, "@string.special.vimdoc", { link = "@constant" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "@tag" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "@punctuation" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Special" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "StorageClass" })
hi(0, "@variable", { fg = "#c1c1c1" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { fg = "#bfc983" })
hi(0, "Beacon", { bg = "#e5e5e5" })
hi(0, "Bold", { bold = true })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { link = "FloatTitle" })
hi(0, "BqfSign", { fg = "#8cd4ae" })
hi(0, "BufferCurrent", { bg = "#121212", bold = true, fg = "#c1c1c1" })
hi(0, "BufferCurrentIcon", { bg = "#121212" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#2c2c2c", bold = true, fg = "#c1c1c1" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#464646", bold = true, fg = "#c1c1c1" })
hi(0, "BufferInactive", { bg = "#0a0a0a", fg = "#c1c1c1" })
hi(0, "BufferInactiveIcon", { bg = "#0a0a0a" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#2c2c2c", fg = "#c1c1c1" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#464646", fg = "#c1c1c1" })
hi(0, "BufferLineBuffer", { fg = "#868686" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c1c1c1" })
hi(0, "BufferLineBufferVisible", { fg = "#c1c1c1" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#b1bc66", fg = "#1e1e1e" })
hi(0, "BufferLineTabSelected", { bg = "#b1bc66", bold = true, fg = "#1e1e1e" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#b1bc66", bold = true, fg = "#1e1e1e" })
hi(0, "BufferVisible", { bg = "#121212", bold = true, fg = "#c1c1c1" })
hi(0, "BufferVisibleIcon", { bg = "#121212" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#2c2c2c", bold = true, fg = "#c1c1c1" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#464646", bold = true, fg = "#c1c1c1" })
hi(0, "Changed", { fg = "#8cd4ae" })
hi(0, "CmpItemAbbr", { fg = "#c1c1c1" })
hi(0, "CmpItemAbbrDefault", { fg = "#c1c1c1" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#868686" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c1c1c1" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c1c1c1" })
hi(0, "CmpItemKind", { fg = "#c1c1c1" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindClassIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindDefault", { fg = "#8cd4ae" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindIconDefault", { fg = "#8cd4ae" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemMenu", { fg = "#c1c1c1" })
hi(0, "CmpItemMenuDefault", { fg = "#c1c1c1" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#94c6fa" })
hi(0, "CocMenuSel", { bg = "#464646" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#94c6fa" })
hi(0, "CocSelectedText", { fg = "#d8be79" })
hi(0, "ColorColumn", { bg = "#464646" })
hi(0, "Comment", { fg = "#868686" })
hi(0, "Conceal", { fg = "#71d3dd" })
hi(0, "Constant", { fg = "#e5acd8" })
hi(0, "CurSearch", { bg = "#cfb059", fg = "#1e1e1e" })
hi(0, "Cursor", { bg = "#b3b3b3", fg = "#1e1e1e" })
hi(0, "CursorColumn", { bg = "#2c2c2c" })
hi(0, "CursorLine", { bg = "#2c2c2c" })
hi(0, "CursorLineFold", { fg = "#525252" })
hi(0, "CursorLineNr", { bold = true, fg = "#c1c1c1" })
hi(0, "CursorLineSign", { fg = "#525252" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#bfc983" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#ebb481" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortcut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#bfc983" })
hi(0, "DefinitionsIcon", { fg = "#71d3dd" })
hi(0, "Delimiter", { fg = "#ebb481" })
hi(0, "DiagnosticDeprecated", { sp = "#f29695", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#f5aaa9" })
hi(0, "DiagnosticFloatingError", { bg = "#0a0a0a", fg = "#f5aaa9" })
hi(0, "DiagnosticFloatingHint", { bg = "#0a0a0a", fg = "#8cd4ae" })
hi(0, "DiagnosticFloatingInfo", { bg = "#0a0a0a", fg = "#94c6fa" })
hi(0, "DiagnosticFloatingOk", { bg = "#0a0a0a", fg = "#bfc983" })
hi(0, "DiagnosticFloatingWarn", { bg = "#0a0a0a", fg = "#d8be79" })
hi(0, "DiagnosticHint", { fg = "#8cd4ae" })
hi(0, "DiagnosticInfo", { fg = "#94c6fa" })
hi(0, "DiagnosticOk", { fg = "#bfc983" })
hi(0, "DiagnosticUnderlineError", { sp = "#f29695", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6fc99b", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#79b8f8", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#b1bc66", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#cfb059", underline = true })
hi(0, "DiagnosticWarn", { fg = "#d8be79" })
hi(0, "DiffAdd", { bg = "#333804" })
hi(0, "DiffChange", { bg = "#265c42" })
hi(0, "DiffDelete", { bg = "#45030d" })
hi(0, "DiffFile", { fg = "#d8be79" })
hi(0, "DiffText", { bg = "#584508" })
hi(0, "Directory", { fg = "#71d3dd" })
hi(0, "EndOfBuffer", { fg = "#525252" })
hi(0, "Error", { bg = "#45030d" })
hi(0, "ErrorMsg", { fg = "#f5aaa9" })
hi(0, "FinderParam", { fg = "#d8be79" })
hi(0, "FinderSpinner", { fg = "#bfc983" })
hi(0, "FinderSpinnerBorder", { fg = "#c1c1c1" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#ebb481" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#0a0a0a", fg = "#c1c1c1" })
hi(0, "FloatShadow", { bg = "#4f5355", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#4f5355", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#0a0a0a", bold = true, fg = "#c1c1c1" })
hi(0, "FoldColumn", { fg = "#525252" })
hi(0, "Folded", { bg = "#0a0a0a", fg = "#868686" })
hi(0, "Function", { fg = "#71d3dd" })
hi(0, "FzfLuaBackdrop", { bg = "#000000" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#c4fff5" })
hi(0, "FzfLuaBufFlagCur", { fg = "#e8804b" })
hi(0, "FzfLuaBufNr", { fg = "#fffcf4" })
hi(0, "FzfLuaHeaderBind", { fg = "#fffcf4" })
hi(0, "FzfLuaHeaderText", { fg = "#e8804b" })
hi(0, "FzfLuaLivePrompt", { fg = "#ff9b9b" })
hi(0, "FzfLuaLiveSym", { fg = "#ff9b9b" })
hi(0, "FzfLuaPathColNr", { fg = "#c4fff5" })
hi(0, "FzfLuaPathLineNr", { fg = "#cff191" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#fffcf4" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#cceff7" })
hi(0, "GitSignsAdd", { fg = "#bfc983" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#d8be79" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#f5aaa9" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#656a4d" })
hi(0, "GitSignsStagedAddCul", { fg = "#656a4d" })
hi(0, "GitSignsStagedAddLn", { fg = "#656a4d" })
hi(0, "GitSignsStagedAddNr", { fg = "#656a4d" })
hi(0, "GitSignsStagedChange", { fg = "#706648" })
hi(0, "GitSignsStagedChangeCul", { fg = "#706648" })
hi(0, "GitSignsStagedChangeLn", { fg = "#706648" })
hi(0, "GitSignsStagedChangeNr", { fg = "#706648" })
hi(0, "GitSignsStagedChangedelete", { fg = "#706648" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#706648" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#706648" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#706648" })
hi(0, "GitSignsStagedDelete", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedTopdeleteLn", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7a5d5d" })
hi(0, "GitSignsStagedUntracked", { fg = "#456d71" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#656a4d" })
hi(0, "GitSignsStagedUntrackedLn", { fg = "#456d71" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#656a4d" })
hi(0, "GitSignsUntracked", { fg = "#71d3dd" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#bfc983", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#ebb481", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#a4a4a4", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#d8be79", nocombine = true })
hi(0, "HopUnmatched", { fg = "#525252" })
hi(0, "HydraAmaranth", { fg = "#e5acd8" })
hi(0, "HydraBlue", { fg = "#71d3dd" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#ebb481" })
hi(0, "HydraRed", { fg = "#f5aaa9" })
hi(0, "HydraTeal", { fg = "#8cd4ae" })
hi(0, "Identifier", { fg = "#d8be79" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#cfb059", fg = "#1e1e1e" })
hi(0, "IndentBlanklineChar", { fg = "#525252", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#c1c1c1", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#b3b3b3", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#94c6fa", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#8cd4ae", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#d8be79", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#f5aaa9", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#71d3dd", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#bfc983", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#ebb481", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#e5acd8", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#c1c1c1" })
hi(0, "LazyButton", { bg = "#2c2c2c" })
hi(0, "LazyButtonActive", { bg = "#464646" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#464646", bold = true, fg = "#c1c1c1" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#d8be79", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#8cd4ae", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#bfc983", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#525252" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#464646" })
hi(0, "LspSagaAutoPreview", { fg = "#94c6fa" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#c1c1c1" })
hi(0, "LspSagaCodeActionContent", { fg = "#c1c1c1" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#71d3dd" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#c1c1c1" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#c1c1c1" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#ebb481" })
hi(0, "LspSagaFinderSelection", { fg = "#8cd4ae" })
hi(0, "LspSagaHoverBorder", { fg = "#c1c1c1" })
hi(0, "LspSagaLspFinderBorder", { fg = "#c1c1c1" })
hi(0, "LspSagaRenameBorder", { fg = "#c1c1c1" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#c1c1c1" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MasonError", { fg = "#f5aaa9" })
hi(0, "MasonHeader", { bg = "#44c8d5", bold = true, fg = "#1e1e1e" })
hi(0, "MasonHeaderSecondary", { bg = "#79b8f8", bold = true, fg = "#1e1e1e" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#c1c1c1" })
hi(0, "MasonHighlightBlock", { bg = "#b3b3b3", fg = "#1e1e1e" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#44c8d5", fg = "#1e1e1e" })
hi(0, "MasonHighlightSecondary", { fg = "#71d3dd" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#464646", fg = "#1e1e1e" })
hi(0, "MasonMutedBlockBold", { bg = "#464646", bold = true, fg = "#1e1e1e" })
hi(0, "MatchParen", { bg = "#464646", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { bg = "#464646" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffSignAdd", { link = "diffAdded" })
hi(0, "MiniDiffSignChange", { link = "diffChanged" })
hi(0, "MiniDiffSignDelete", { link = "diffRemoved" })
hi(0, "MiniFilesFile", { fg = "#c1c1c1" })
hi(0, "MiniFilesTitleFocused", { bg = "#0a0a0a", bold = true, fg = "#c1c1c1" })
hi(0, "MiniHipatternsFixme", { bg = "#f29695", bold = true, fg = "#1e1e1e" })
hi(0, "MiniHipatternsHack", { bg = "#cfb059", bold = true, fg = "#1e1e1e" })
hi(0, "MiniHipatternsNote", { bg = "#6fc99b", bold = true, fg = "#1e1e1e" })
hi(0, "MiniHipatternsTodo", { bg = "#79b8f8", bold = true, fg = "#1e1e1e" })
hi(0, "MiniIconsAzure", { fg = "#71d3dd" })
hi(0, "MiniIconsBlue", { fg = "#94c6fa" })
hi(0, "MiniIconsCyan", { fg = "#8cd4ae" })
hi(0, "MiniIconsGreen", { fg = "#bfc983" })
hi(0, "MiniIconsGrey", { fg = "#dadada" })
hi(0, "MiniIconsOrange", { fg = "#ebb481" })
hi(0, "MiniIconsPurple", { fg = "#e5acd8" })
hi(0, "MiniIconsRed", { fg = "#f5aaa9" })
hi(0, "MiniIconsYellow", { fg = "#d8be79" })
hi(0, "MiniIndentscopeSymbol", { fg = "#c1c1c1" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#f5aaa9" })
hi(0, "MiniJump", { sp = "#b3b3b3", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#525252" })
hi(0, "MiniJump2dSpot", { bg = "#030303", bold = true, fg = "#f3f3f3", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#030303", fg = "#dadada", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#0a0a0a", fg = "#868686" })
hi(0, "MiniMapSymbolCount", { fg = "#868686" })
hi(0, "MiniMapSymbolLine", { fg = "#c1c1c1" })
hi(0, "MiniMapSymbolView", { fg = "#c1c1c1" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniSnippetsCurrent", { sp = "#cfb059", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#f29695", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#b1bc66", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#6fc99b", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#79b8f8", underdouble = true })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#c1c1c1" })
hi(0, "MiniStarterItemBullet", { fg = "#868686" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#d8be79" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#bfc983" })
hi(0, "MiniStarterSection", { fg = "#e5acd8" })
hi(0, "MiniStatuslineDevinfo", { bg = "#2c2c2c", fg = "#a4a4a4" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#121212", fg = "#a4a4a4" })
hi(0, "MiniStatuslineModeCommand", { bg = "#cfb059", bold = true, fg = "#1e1e1e" })
hi(0, "MiniStatuslineModeInsert", { bg = "#44c8d5", bold = true, fg = "#1e1e1e" })
hi(0, "MiniStatuslineModeNormal", { bg = "#b3b3b3", bold = true, fg = "#1e1e1e" })
hi(0, "MiniStatuslineModeOther", { bg = "#6fc99b", bold = true, fg = "#1e1e1e" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f29695", bold = true, fg = "#1e1e1e" })
hi(0, "MiniStatuslineModeVisual", { bg = "#b1bc66", bold = true, fg = "#1e1e1e" })
hi(0, "MiniTablineCurrent", { bg = "#121212", bold = true, fg = "#c1c1c1" })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#0a0a0a", fg = "#a4a4a4" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#b3b3b3", bold = true, fg = "#1e1e1e" })
hi(0, "MiniTablineModifiedHidden", { bg = "#979797", fg = "#161616" })
hi(0, "MiniTablineModifiedVisible", { bg = "#979797", bold = true, fg = "#161616" })
hi(0, "MiniTablineTabpagesection", { bg = "#b1bc66", bold = true, fg = "#1e1e1e" })
hi(0, "MiniTablineVisible", { bg = "#0a0a0a", bold = true, fg = "#a4a4a4" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#f5aaa9" })
hi(0, "MiniTestPass", { bold = true, fg = "#bfc983" })
hi(0, "MiniTrailspace", { bg = "#45030d" })
hi(0, "ModeMsg", { fg = "#bfc983" })
hi(0, "MoreMsg", { fg = "#71d3dd" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#464646", fg = "#868686" })
hi(0, "NeoTreeDimText", { fg = "#525252" })
hi(0, "NeoTreeDotfile", { fg = "#a4a4a4" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#525252" })
hi(0, "NeoTreeGitAdded", { fg = "#bfc983" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#ebb481" })
hi(0, "NeoTreeGitDeleted", { fg = "#f5aaa9" })
hi(0, "NeoTreeGitModified", { fg = "#d8be79" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e5acd8" })
hi(0, "NeoTreeGitUntracked", { fg = "#8cd4ae" })
hi(0, "NeoTreeMessage", { bg = "#2c2c2c", fg = "#c1c1c1" })
hi(0, "NeoTreeModified", { fg = "#dadada" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#c1c1c1" })
hi(0, "NeoTreeTabInactive", { fg = "#868686" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#464646", fg = "#868686" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#2c2c2c", fg = "#373737" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#c1c1c1" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#c1c1c1" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#71d3dd" })
hi(0, "NoiceConfirmBorder", { fg = "#d8be79" })
hi(0, "NonText", { fg = "#525252" })
hi(0, "Normal", { bg = "#121212", fg = "#c1c1c1" })
hi(0, "NormalFloat", { bg = "#0a0a0a", fg = "#c1c1c1" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#bfc983" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#f5aaa9" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#94c6fa" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#8cd4ae" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#d8be79" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimInternalError", { bg = "#d26518", ctermbg = 9, ctermfg = 9, fg = "#d37b49" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#bfc983" })
hi(0, "NvimTreeFolderIcon", { fg = "#868686" })
hi(0, "NvimTreeGitDeleted", { fg = "#f5aaa9" })
hi(0, "NvimTreeGitDirty", { fg = "#d8be79" })
hi(0, "NvimTreeGitMerge", { fg = "#ebb481" })
hi(0, "NvimTreeGitNew", { fg = "#8cd4ae" })
hi(0, "NvimTreeGitRenamed", { fg = "#e5acd8" })
hi(0, "NvimTreeGitStaged", { fg = "#bfc983" })
hi(0, "NvimTreeImageFile", { fg = "#ebb481" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#c1c1c1" })
hi(0, "NvimTreeSpecialFile", { fg = "#c1c1c1", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#94c6fa" })
hi(0, "NvimTreeWindowPicker", { bg = "#464646", bold = true, fg = "#c1c1c1" })
hi(0, "Operator", { fg = "#c1c1c1" })
hi(0, "OutlineDetail", { fg = "#525252" })
hi(0, "OutlineFoldPrefix", { fg = "#d8be79" })
hi(0, "OutlineIndentEvn", { fg = "#868686" })
hi(0, "OutlineIndentOdd", { fg = "#c1c1c1" })
hi(0, "Pmenu", { bg = "#2c2c2c", fg = "#c1c1c1" })
hi(0, "PmenuMatch", { bg = "#2c2c2c", bold = true, fg = "#c1c1c1" })
hi(0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
hi(0, "PmenuThumb", { bg = "#464646" })
hi(0, "PounceAccept", { bg = "#cfb059", bold = true, fg = "#1e1e1e", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#b1bc66", bold = true, fg = "#1e1e1e", nocombine = true })
hi(0, "PounceGap", { bg = "#464646", bold = true, fg = "#1e1e1e", nocombine = true })
hi(0, "PounceMatch", { bg = "#b3b3b3", bold = true, fg = "#1e1e1e", nocombine = true })
hi(0, "PreProc", { fg = "#94c6fa" })
hi(0, "Question", { fg = "#71d3dd" })
hi(0, "QuickFixLine", { bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#71d3dd" })
hi(0, "RainbowDelimiterCyan", { fg = "#8cd4ae" })
hi(0, "RainbowDelimiterGreen", { fg = "#bfc983" })
hi(0, "RainbowDelimiterOrange", { fg = "#ebb481" })
hi(0, "RainbowDelimiterRed", { fg = "#f5aaa9" })
hi(0, "RainbowDelimiterViolet", { fg = "#e5acd8" })
hi(0, "RainbowDelimiterYellow", { fg = "#d8be79" })
hi(0, "RedrawDebugClear", { bg = "#69530b", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#335008", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#4b1b03", ctermbg = 9, ctermfg = 0 })
hi(0, "References", { fg = "#bfc983" })
hi(0, "ReferencesIcon", { fg = "#71d3dd" })
hi(0, "Removed", { fg = "#f5aaa9" })
hi(0, "Search", { bg = "#b3b3b3", fg = "#1e1e1e" })
hi(0, "SignColumn", { fg = "#525252" })
hi(0, "Sneak", { bg = "#e4a464", fg = "#1e1e1e" })
hi(0, "SneakLabel", { bg = "#e4a464", bold = true, fg = "#1e1e1e" })
hi(0, "SneakScope", { bg = "#e5e5e5", fg = "#1e1e1e" })
hi(0, "SnippetTabstop", { bg = "#584508" })
hi(0, "Special", { fg = "#8cd4ae" })
hi(0, "SpecialKey", { fg = "#525252" })
hi(0, "SpellBad", { sp = "#f29695", undercurl = true })
hi(0, "SpellCap", { sp = "#6fc99b", undercurl = true })
hi(0, "SpellLocal", { sp = "#cfb059", undercurl = true })
hi(0, "SpellRare", { sp = "#79b8f8", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#c1c1c1" })
hi(0, "StatusLine", { bg = "#121212", fg = "#a4a4a4" })
hi(0, "StatusLineNC", { bg = "#0a0a0a", fg = "#a4a4a4" })
hi(0, "String", { fg = "#bfc983" })
hi(0, "Substitute", { bg = "#79b8f8", fg = "#1e1e1e" })
hi(0, "TabLine", { bg = "#0a0a0a", fg = "#a4a4a4" })
hi(0, "TabLineSel", { bg = "#0a0a0a", fg = "#c1c1c1" })
hi(0, "TargetFileName", { fg = "#c1c1c1" })
hi(0, "TelescopeBorder", { fg = "#c1c1c1" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#464646" })
hi(0, "TelescopeSelection", { bg = "#2c2c2c" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#c1c1c1" })
hi(0, "Todo", { bg = "#121212", bold = true, fg = "#c1c1c1" })
hi(0, "TroubleCount", { bold = true, fg = "#c1c1c1" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#c1c1c1" })
hi(0, "TroubleIndent", { fg = "#525252" })
hi(0, "TroubleLocation", { fg = "#a4a4a4" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#c1c1c1" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#c1c1c1" })
hi(0, "VenvSelectActiveVenv", { fg = "#cdf367" })
hi(0, "VertSplit", { fg = "#c1c1c1" })
hi(0, "Visual", { bg = "#464646" })
hi(0, "VisualNOS", { bg = "#2c2c2c" })
hi(0, "WarningMsg", { fg = "#d8be79" })
hi(0, "WhichKey", { fg = "#8cd4ae" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#c1c1c1" })
hi(0, "WhichKeyFloat", { bg = "#0a0a0a", fg = "#c1c1c1" })
hi(0, "WhichKeyGroup", { fg = "#f5aaa9" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeySeparator", { fg = "#bfc983" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#525252" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#c1c1c1" })
hi(0, "diffAdded", { fg = "#bfc983" })
hi(0, "diffChanged", { fg = "#8cd4ae" })
hi(0, "diffLine", { fg = "#94c6fa" })
hi(0, "diffRemoved", { fg = "#f5aaa9" })
hi(0, "gitcommitBranch", { bold = true, fg = "#ebb481" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#d8be79" })
hi(0, "gitcommitDiscardedType", { fg = "#71d3dd" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#d8be79" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#bfc983" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#bfc983" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#8cd4ae" })
hi(0, "lCursor", { bg = "#b3b3b3", fg = "#1e1e1e" })
hi(0, "lualine_a_command", { bg = "#e3c162", bold = true, fg = "#1f1f1f" })
hi(0, "lualine_a_inactive", { bg = "#4d4d4d", bold = true, fg = "#a7a7a7" })
hi(0, "lualine_a_insert", { bg = "#c2cd6f", bold = true, fg = "#1f1f1f" })
hi(0, "lualine_a_normal", { bg = "#4d4d4d", bold = true, fg = "#a7a7a7" })
hi(0, "lualine_a_replace", { bg = "#f5a6e4", bold = true, fg = "#1f1f1f" })
hi(0, "lualine_a_terminal", { bg = "#e3c162", bold = true, fg = "#1f1f1f" })
hi(0, "lualine_a_visual", { bg = "#78ddaa", bold = true, fg = "#1f1f1f" })
hi(0, "lualine_b_command", { bg = "#131313", fg = "#ecd083" })
hi(0, "lualine_b_diagnostics_error_command", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_error_inactive", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_error_insert", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_error_normal", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_error_replace", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_error_terminal", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_error_visual", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diagnostics_hint_command", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_hint_inactive", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_hint_insert", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_hint_normal", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_hint_replace", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_hint_terminal", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_hint_visual", { bg = "#131313", fg = "#8cd4ae" })
hi(0, "lualine_b_diagnostics_info_command", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_info_inactive", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_info_insert", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_info_normal", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_info_replace", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_info_terminal", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_info_visual", { bg = "#131313", fg = "#94c6fa" })
hi(0, "lualine_b_diagnostics_warn_command", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diagnostics_warn_inactive", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diagnostics_warn_insert", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diagnostics_warn_normal", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diagnostics_warn_replace", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diagnostics_warn_terminal", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diagnostics_warn_visual", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_added_command", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_added_inactive", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_added_insert", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_added_normal", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_added_replace", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_added_terminal", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_added_visual", { bg = "#131313", fg = "#bfc983" })
hi(0, "lualine_b_diff_modified_command", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_modified_inactive", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_modified_insert", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_modified_normal", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_modified_replace", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_modified_terminal", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_modified_visual", { bg = "#131313", fg = "#d8be79" })
hi(0, "lualine_b_diff_removed_command", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diff_removed_inactive", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diff_removed_insert", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diff_removed_normal", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diff_removed_replace", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diff_removed_terminal", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_diff_removed_visual", { bg = "#131313", fg = "#f5aaa9" })
hi(0, "lualine_b_inactive", { bg = "#131313", fg = "#6e6e6e" })
hi(0, "lualine_b_insert", { bg = "#131313", fg = "#cfdb8d" })
hi(0, "lualine_b_normal", { bg = "#131313", fg = "#6e6e6e" })
hi(0, "lualine_b_replace", { bg = "#131313", fg = "#fbb9ec" })
hi(0, "lualine_b_terminal", { bg = "#131313", fg = "#ecd083" })
hi(0, "lualine_b_visual", { bg = "#131313", fg = "#97e7bd" })
hi(0, "lualine_c_command", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_c_inactive", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_c_insert", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_c_normal", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_c_replace", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_c_terminal", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_c_visual", { bg = "#131313", fg = "#d2d2d2" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#131313", fg = "#ecd083" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_c_command", { bg = "#131313", fg = "#ecd083" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#131313", fg = "#595959" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_c_normal", { bg = "#131313", fg = "#595959" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#121212"
g.terminal_color_1 = "#f5aaa9"
g.terminal_color_2 = "#bfc983"
g.terminal_color_3 = "#d8be79"
g.terminal_color_4 = "#94c6fa"
g.terminal_color_5 = "#fbb9ec"
g.terminal_color_6 = "#97e7bd"
g.terminal_color_7 = "#d2d2d2"
g.terminal_color_8 = "#444444"
g.terminal_color_9 = "#f5aaa9"
g.terminal_color_10 = "#bfc983"
g.terminal_color_11 = "#d8be79"
g.terminal_color_12 = "#94c6fa"
g.terminal_color_13 = "#fbb9ec"
g.terminal_color_14 = "#97e7bd"
g.terminal_color_15 = "#d2d2d2"
